### ISSUE TITLE
Umgang mit Freitextfeldern bei der Erfassung von "Other"

### ISSUE THREAD

**Issue by chrmey** [hl7germany/forschungsnetz-covid19#100]
Bsp.: IG Chronic Lung Diseases

PARAMETER CASE REPORT FORM | RESPONSE OPTIONS
-- | --
Does the patient suffer from a chronic lung disease? | Asthma / COPD / Fibrosis of lung / Pulmonary hypertension / Extreme  obesity with alveolar hypoventilation / Sleep apnea / Obstructive sleep  apnea syndrome / Cystic fibrosis / Other / No / Unknown

Was soll passieren wenn "Other" ausgewählt wird? Das wird im IG nicht abgedeckt/erwähnt/spezifiziert.
1) Freitextfeld  (Text) -> Eingabe nicht prüfbar, Problematisch bei Pseudonymisierung (Datenschutz) --> Kein Mehrwert
2) ICD-Auswahlfeld -> ICDs zur Kategorie aus folgenden Value-Sets auswählbar: 

    + Include codes from Icd-10-gm where concept IsA G47.3 
    + Include codes from Icd-10-gm where concept IsA E66.2 
    + Include codes from Icd-10-gm where concept IsA I27 
    + Include codes from Icd-10-gm where concept IsA J62 
    + Include codes from Icd-10-gm where concept IsA J63 
    + Include codes from Icd-10-gm where concept IsA J44 
    + Include codes from Icd-10-gm where concept IsA J45 
    + Include codes from Icd-10-gm where concept IsA E84 

**Wie soll dort vorgegangen werden und wie werden die erfassten Daten abgebildet?**

Freitext in Condition.note.text ? 
Was wäre für den Fall, wenn ein ICD erfasst wird?

**Comment by cerbelding** [comment]
Bezüglich der Codierung von "Andere", sowie der Abbildung der Freitext-Felder verweise ich auf die Issues #86 und #97.
Dort ist beschrieben, wie das Mapping für den `ODM2FHIR`-Mapper gelöst wurde.

**Comment by chrmey** [comment]
Das leuchtet ein, aber soll trotzdem ein Freitext erfasst werden oder reicht ein "Andere" mit den Codes? Ein Freitext bietet hier aus meiner Sicht keinen Mehrwert. Auch weil das Freitextfeld nicht gefiltert werden kann und somit bei Pseudonymisierungsschritten für uns jedenfalls eh rausfällt.

**Comment by cerbelding** [comment]
Wir übernehmen den Freitext aktuell als `Condition.Code.Text`, einen  Mehrwert bietet dies allerdings nicht.

**Comment by chrmey** [comment]
Okay, danke.

**Comment by julsas** [comment]
Idealerweise würde man die 'anderen' strukturiert erfassen. Deswegen erlauben die ValueSets da die Codes, wo der passende SNOMED/ICD wahrscheinlich zu finden ist. Die sind dann in FHIR so zu erfassen, wie man mit den explizit aufgeführten Codes auch umgeht. Wenn man nur die Freitexte hat, dann vorgehen wie @cerbelding das umgesetzt hat. Ich kann nicht bewerten, wie viel Mehrwert das am Ende generiert. Für maximalen Mehrwert müsste man wohl direkt auf SNOMED matchen.
