### ISSUE TITLE
Erstellung der Imaging Procedures und Radiological Findings

### ISSUE THREAD

**Issue by riejo** [hl7germany/forschungsnetz-covid19#101]
Werden nur Procedures für das jeweilige Verfahren erstellt, wenn dieses auch durchgeführt wurde? In Simplifer gibt es nur für diesen Fall Beispiele.
**Wenn im GECCO-Formular „nein“ oder „unbekannt“ angekreuzt wurde, würde es dann keine entsprechende Ressource geben? Dieselbe Frage stellt sich für die entsprechende DiagnosticReport-Ressource.** 

Es gibt das Element "performed[x]", in welchem der Zeitpunkt der Durchführung vorhanden sein soll. 
![performed](https://user-images.githubusercontent.com/79310839/108496910-0859a980-72ab-11eb-9dfc-8c252ab29e08.PNG)

**Im Formular gibt es aber keine Möglichkeit, dieses einzutragen.**
![Bildgebung](https://user-images.githubusercontent.com/79310839/108494604-08a47580-72a8-11eb-97a8-3202ca2cc115.PNG)

**Comment by cerbelding** [comment]
Es können auch Ressourcen erstellt werden, welche eine negative Antwort abbilden.

Hierzu gibt es das [ValueSet `EventStatus`](https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/80010), welches als `required`-Binding dem `Procedure.status` zugewiesen ist.
Lediglich RadiologicalFindings als `DiagnosticReport` wird im Nein/Unbekannt Fall nicht erstellt.

Zum `performed`-Datum kann ich Ihnen leider nichts sagen. Diesem Problem stehen wir ebenfalls gegenüber.

**Comment by cerbelding** [comment]
Zum Datum: siehe Issue #99

**Comment by julsas** [comment]
Ich würde nur die positiv Ressourcen generieren, weil hier bei den Antwortmöglichkeiten kein 'Nein' oder 'Unbekannt' vorgegeben war. Über status wäre aber 'not-done' oder 'unknown' möglich. Dann muss performed[x] mit data-absent-reason beantwortet werden. Nach #99 sollte data-absent jetzt auch validieren.

**Comment by riejo** [comment]
Ist dies eine feste Vorgabe, welche im IG beschrieben wird, oder ist dies standortabhängig und jeder kann selbst regeln, ob man diese anlegt? Oder ist es generell vorgesehen, ausschließlich positiv Ressourcen zu erstellen?
