### ISSUE TITLE
Identifier in Observations

### ISSUE THREAD

**Issue by chrmey** [hl7germany/forschungsnetz-covid19#102]
In Observation sind im IG eigene Identifier genannt wie:

*2019-08_paCO2*

![grafik](https://user-images.githubusercontent.com/47111421/108496515-72be1a00-72aa-11eb-9e4e-005546dcae7f.png)

Wozu soll dieser Identifier dienen, vor Allem weil der ein Pflichtfeld ist? Dient das zum Gruppieren von gleichen Parametern die verschiedene LOINC Codes aufgrund des Messverfahrens/Einheit haben können? Wenn dem so ist, müsste es dafür eine Vorschrift geben wie diese Identifier auszusehen haben. 
Oder dient der einfach dazu, einen einzigen Labormesswert identifizieren zu können?

**Comment by cerbelding** [comment]
siehe Issue #96

**Comment by chrmey** [comment]
An der Stelle wäre dann im GECCO-IG ein Verweis auf den Hinweis zum MII-Labor-IG hilfreich.

**Comment by julsas** [comment]
Ja guter Hinweis. Habe einen Link auf den MII IG reingenommen.

**Comment by chrmey** [comment]
Das betrifft neben den Laborwerten auch noch die Kategorie "vital-signs" da müsste der Hinweis auch rein.

**Comment by julsas** [comment]
Die Items unter VitalSigns auf Basis MII Labor haben jetzt auch den Link drin.
