### ISSUE TITLE
Welche Patienten Ressource ist zu verwenden?

### ISSUE THREAD

**Issue by chrmey** [hl7germany/forschungsnetz-covid19#103]
Aus dem IG geht nicht direkt hervor, welches Profile verwendet werden soll um einen Patienten abzubilden. Das müsste ergänzt werden.

**Comment by cerbelding** [comment]
Wie im [Abschnitt `TransactionBundle`](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/TransactionBundle) im Simplifier-IG beschrieben, wird das Profil https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/Patient genutzt

**Comment by chrmey** [comment]
Okay, danke. Es wäre hier hilfreich, wenn das Patienten Profil auch im Baum vorkommt und nicht "beiläufig" in einer Transaktion erwähnt wird. Das geht da leider schnell unter.

**Comment by julsas** [comment]
Unter Demographics bei Date of birth und age im Baum ist die Patienten-Ressource.

**Comment by chrmey** [comment]
Kann irgendwo ein Hinweis eingefügt werden, dass die Patienten Ressource dort zu finden ist? Die ging so einfach ziemlich unter.
