### ISSUE TITLE
Fallbezug der Ressourcen

### ISSUE THREAD

**Issue by chrmey** [hl7germany/forschungsnetz-covid19#104]
Es geht nicht aus dem IG hervor, wie ein Fallbezug hergestellt wird. Laut IG wird gar keiner hergestellt. Wie sollen Daten für einen Patienten mit zwei Covid-Fällen abgebildet werden?

**Comment by julsas** [comment]
Die Vorgaben zu dem Datensatz enthalten keinen Fall, deswegen gibt es keine Encounter-Ressource oder ähnliches. Die Daten müssen über die Patienten-Ressource zusammengeführt werden.

**Comment by chrmey** [comment]
Dann wird also der GECCO Datensatz bei einem zweiten Covid-Fall eines Patienten um die neuen Datenelemente erweitert?

**Comment by riejo** [comment]
In der Datei "report_German_COVID19_Consensus_Dataset.pdf" wurde erwähnt, dass eine Encounter-Ressource im Core Data Set enthalten ist
![encounter](https://user-images.githubusercontent.com/79310839/108966517-8ee10300-767e-11eb-9c1a-05d9aa764783.PNG)


Es scheint sich um eine veraltete Version zu handeln (wurde zuletzt vor 4 Monaten aktualisiert), jedoch stellt sich mir die Frage, wieso diese herausgenommen / nicht umgesetzt wurde?

**Comment by julsas** [comment]
> Dann wird also der GECCO Datensatz bei einem zweiten Covid-Fall eines Patienten um die neuen Datenelemente erweitert?

Ja über die Referenzen auf Patient.

**Comment by julsas** [comment]
> Es scheint sich um eine veraltete Version zu handeln (wurde zuletzt vor 4 Monaten aktualisiert), jedoch stellt sich mir die Frage, wieso diese herausgenommen / nicht umgesetzt wurde?

Das PDF ist von Juni 2020. Da hatten wir mit der FHIR Umsetzung gerade angefangen. Der Punkt Consent wurde später auch gestrichen. U.a. haben wir Encounter rausgenommen, weil wir wenn möglich auf die MII-Module setzen wollten. Da ist das Fall-Modul mit dem Encounter aber nicht fertig.

**Comment by riejo** [comment]
> Ja über die Referenzen auf Patient.

Wie genau kann man bei der Referenz auf einen Patient bestimmen, dass es sich um zwei unterschiedliche Fälle, aber um denselben Patient handelt?

**Comment by julsas** [comment]
> Wie genau kann man bei der Referenz auf einen Patient bestimmen, dass es sich um zwei **unterschiedliche Fälle**, aber um denselben Patient handelt?

Kann man nicht, da es keinen Fall gibt. Man kann nur sagen, dass es um denselben Patient geht.

**Comment by riejo** [comment]
> Kann man nicht, da es keinen Fall gibt. Man kann nur sagen, dass es um denselben Patient geht.

Wie genau wird dann die Information erfasst, dass ein Patient zwei oder mehrere unterschiedliche Male aufgrund einer Covid-Erkrankung eingeliefert wurde? Bzw. wie kann man erkennen, dass die Ressourcen von unterschiedlichen Fällen/Perioden stammen, wenn es keinen Fall gibt? Oder ist eine solche Unterscheidung generell nicht vorgesehen?

**Comment by julsas** [comment]
> Wie genau wird dann die Information erfasst, dass ein Patient zwei oder mehrere unterschiedliche Male aufgrund einer Covid-Erkrankung eingeliefert wurde? Bzw. wie kann man erkennen, dass die Ressourcen von unterschiedlichen Fällen/Perioden stammen, wenn es keinen Fall gibt? Oder ist eine solche Unterscheidung generell nicht vorgesehen?

Die zeitliche Periode bekommt man über die Zeitstempel in den Ressourcen. Ein Fall-Konzept ist bislang nicht vorgesehen.
