### ISSUE TITLE
Impfungsstatus

### ISSUE THREAD

**Issue by riejo** [hl7germany/forschungsnetz-covid19#105]
Auf Simplifier gibt es nur Immunization-Beispiele für die beiden Fälle, das entweder eine Impfung bekannt ist oder dass gar keine Impfungen bekannt sind. 
**Was passiert, wenn unter einer spezifischen Impfung (z.B. Influenza) „nein“ bzw. „unbekannt“ angegeben wird.**
![impfungen](https://user-images.githubusercontent.com/79310839/108497179-5a9aca80-72ab-11eb-8f29-fa2b0e040cf1.PNG)

**Wird in dem Fall auch eine entsprechende Ressource erstellt?, Wenn ja, welche Elemente würden dazukommen/entfernt werden?**

**Comment by cerbelding** [comment]
Laut Code-Binding dürfen nur die Codes `completed`, `entered-in-error` & `not-done` aus dem ValueSet `EventStatus` als Status verwendet werden.

Eine Abbildung von "Unbekannt" ist also nicht ohne weiteres möglich, eine Ressource macht hier aber wohl auch keinen Sinn.
Für "Nein" kann der Status "not-done" genutzt werden.

**Comment by riejo** [comment]
Danke für die Antwort!
Es wäre sinnvoll, dies irgendwie im IG zu vermerken, damit der Leser sich über die Vorgaben und verschiedenen Fälle ("ja", "nein", "unbekannt") zu 100% im Klaren ist und keine Missverständnisse oder Inkonsistenzen entstehen.

**Comment by julsas** [comment]
In den Vorgaben wurde nur nach vorhandenen Impfungen gefragt, nicht nach Ausschluss. Deswegen gibt es nur positiv Beispiele, oder man weiß es überhaupt nicht. 'not-done' wäre aber möglich, um zu verneinen.

**Comment by riejo** [comment]
Ist es denn für den GECCO-Datensatz letztendlich vorgesehen, dass ausgeschlossene Impfungen beinhaltet werden? Jeder Standort könnte dies sonst unterschiedlich interpretieren und abhängig davon mehr oder weniger Ressourcen übersenden.

**Comment by julsas** [comment]
Bei den Antwortmöglichkeiten ist nicht entahlten, ausgeschlossene Impfungen zu dokumentieren.
