### ISSUE TITLE
Nierenerkankung

### ISSUE THREAD

**Issue by riejo** [hl7germany/forschungsnetz-covid19#106]
**Wird lediglich eine einzige Ressource für die Ausprägung erstellt (z.B. nur für Stadium 3)?**
![nierenerkrankung1](https://user-images.githubusercontent.com/79310839/108497601-faf0ef00-72ab-11eb-87a7-9b4e0603795e.PNG)

**Oder werden dann auch Ressourcen für die anderen Typen erstellt, welche „nicht vorhanden“ aussagen?** Dies ist nicht ersichtlich aus den Beispiel-Ressourcen auf Simplifier.

**Comment by cerbelding** [comment]
Nein, es wird nur eine Ressource erstellt, bei der der Code dann in Abhängigkeit des Schweregrads gesetzt wird.

Wobei die Codierung der Antwort "Ja, mit Hämolyse" etwas schwierig ist, da für den SNOMED-Code `714152005 | Chronic kidney disease stage 5 on dialysis (disorder)` eigentlich 2 ICD-Codes zum Abbilden nötig wären.
