### ISSUE TITLE
Bestehende Sauerstoff- oder Beatmungstherapie

### ISSUE THREAD

**Issue by riejo** [hl7germany/forschungsnetz-covid19#107]
Bei der Procedure-Ressource ist das Element performed[x], unter welchem Angaben zur Zeit gemacht werden, Pflicht. 
![performed](https://user-images.githubusercontent.com/79310839/108497936-73f04680-72ac-11eb-9105-beabd8e06a78.PNG)

**Im Formular gibt es aber keine Möglichkeit, ein Datum anzugeben.**
![beatmung](https://user-images.githubusercontent.com/79310839/108498011-8f5b5180-72ac-11eb-82e9-5ee394ae5735.PNG)

**Was für ein Wert wird in dieses Element eingetragen?**

**Comment by cerbelding** [comment]
Für den `ODM2FHIR` Mapper wird bei allen nicht abgefragten Datumsfeldern eine Data-Absent-Reason-Extension hinzugefügt.

```json
"_performedDateTime": {
    "extension":  [
        {
            "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
            "valueCode": "unknown"
        }
    ]
}
```

**Comment by riejo** [comment]
Das ergibt Sinn.
Vielleicht wäre es besser, dieses in den Beispielen im IG anzugeben, bisher ist dort immer ein Datum verzeichnet:

![performeddate](https://user-images.githubusercontent.com/79310839/108501870-3393c700-72b2-11eb-9ab3-f3e25e3457b7.PNG)
