### ISSUE TITLE
Diabetes

### ISSUE THREAD

**Issue by riejo** [hl7germany/forschungsnetz-covid19#108]
**Es ist nicht ganz ersichtlich, was für Ressourcen erstellt werden:**
wenn der Patient an z.B. Typ 2 leidet, **werden dann auch Conditions zu Typ 1 und Typ 3 erstellt (jeweils mit „refuted“ / „Definitely NOT present (qualifier value)“ im verificationStatus)?**
![diabetes](https://user-images.githubusercontent.com/79310839/108498483-393ade00-72ad-11eb-9f53-0d0518536c7a.PNG)

Wenn der Patient nicht unter Diabetes leidet bzw. dies unbekannt ist, **werden dann entsprechende Ressourcen für alle Typen oder nur eine für Diabetes Mellitus allgemein erstellt?**
![diabetesNein](https://user-images.githubusercontent.com/79310839/108498530-4d7edb00-72ad-11eb-9557-42fd12efefb3.PNG)

**Comment by cerbelding** [comment]
Es wird nur eine Ressource erstellt (entweder die positive mit dem Typ, oder eine allgemeine negative)
Bei "Unbekannt" wird keine Ressource erstellt.

**Comment by riejo** [comment]
Danke für die Antwort.
Auf Simplifier gibt es ein Beispiel für "Unbekannt".
![diabetes_unbekannt](https://user-images.githubusercontent.com/79310839/108501269-570a4200-72b1-11eb-9feb-5ca6c9bcfdc1.PNG)

Wenn in dem Fall keine Ressource erstellt wird, sollte dieses wohl entfernt werden.

**Comment by cerbelding** [comment]
Dass wird mit dem `ODM2FHIR` Mapper hier aktuell keine Ressource erstellen, ist nicht gezwungenermaßen die einzige Lösung.
Wir haben uns dazu entschlossen, da unbekannt und "nicht beantwortet" für die weitere Verarbeitung zum gleichen Ergebnis führen.

Von offizieller Seite gab es hier noch keine Rückmeldung

**Comment by chrmey** [comment]
Okay, gut zu wissen. Sowas muss in meinen Augen unbedingt im IG spezifiziert werden. Das Fehlen einer solchen Spezifikation führt zu Inkonsestenzen und Interpretationsproblemen wenn die Datensätze aus verschiedenen Häusern mit verschiedener Interpretation des IG zusammenkommen. Der IG darf bei sowas eigentlich keinen Interpretationsspielraum lassen.

**Comment by julsas** [comment]
Das Antwortschema ist hier wie bei den anderen Risikofaktoren. Bei den vorgegebenen Antworten soll man Ja/Nein/Unbekannt sagen können. Deswegen gibt es ein Beispiel, welches ausdrückt, dass eine der Antwortmöglichkeiten unbekannt ist.

**Comment by riejo** [comment]
Heißt dies, dass für die Antwortmöglichkeit "unbekannt" definitv eine entsprechende Condition (für Diabetes allgemein) erstellt und in das endgültige GECCO-Bundle integriert wird? Das ist mir bis jetzt noch etwas zu unklar formuliert.

**Comment by julsas** [comment]
Der Vollständigkeit halber würde ich die Unbekannten erfassen. Wie in #109 auch gesagt, gibt es keine Vorgabe dazu. Das Bundle prüft nicht, ob alle Fragen beantwortet sind.

**Comment by riejo** [comment]
Laut dem IG heißt es "The German Corona Consensus Data Set (GECCO) is a nationally uniform data set for the systematic collection of scientific data on COVID-19 in Germany." (erster Satz in Introduction). Dort steht ja drin: "nationally uniform". Ich finde, da sollten klare Vorgaben gemacht werden, welche Ressourcen genau im Datensatz enthalten sind und welche nicht. Am Ende ist auch nicht der Sinn dahinter, dass jede Uniklinik ihre eigene Interpretation des Datensatzes durch die Antworten in Bezug auf „nein“- oder „unbekannt“-Ressourcen schickt. Meiner Meinung nach gefährdet dies die „nationale Uniformität“.
