### ISSUE TITLE
Anamnese/Risikofaktoren

### ISSUE THREAD

**Issue by chrmey** [hl7germany/forschungsnetz-covid19#109]
Anwendungsfall:

Es wird auf die Frage `Leidet der Patient an chronischen Lungenerkrankungen?` bei **Asthma** und **COPD** mit JA geantwortet. 

Ergebnis --> Es wird jeweils eine Ressource erstellt die aussagt dass Asthma und COPD bestehen. 

Was passiert mit den anderen Punkten? Werden dort Ressourcen erzeugt, die z.B. eine Fibrose verneinen oder werden keine Ressourcen generiert? 

Wie soll vorgegangen werden?

**Comment by cerbelding** [comment]
Es wird auch eine negative Ressource für die anderen chron. Lungenerkrankungen erstellt.
Analog bei den anderen Anamnese-Fragen.

**Comment by julsas** [comment]
Die anderen explizit gefragten Punkte, würde ich explizit verneinen, wenn das Vorhandensein ausgeschlossen ist. Für 'andere/other' würde ich nur die positiv Ergebnisse erzeugen.

**Comment by chrmey** [comment]
Was heißt "würde"? Ist das eine konkrete Vorgabe (die auch durch den IG) abgedeckt wird oder soll da jeder Standort für sich selber entscheiden wie er damit umgeht? Da müsste klar definiert sein, damit spätere Auswertungen eben diese Eingrenzung über die Verneinung berücksichtigen können.

**Comment by julsas** [comment]
Es gab datensatzseitig keine Vorgabe, wie vollständig die Daten sein sollen. Um alle vorgegebenen Antworten zu erfassen, 'würde' ich die Daten wie beschrieben erfassen. Der IG erzwingt das nicht, weil es bislang niemand definiert hat.
