### ISSUE TITLE
HIV-Infektion

### ISSUE THREAD

**Issue by riejo** [hl7germany/forschungsnetz-covid19#110]
Im ValueSet gibt es vier ICD-Codes:
![hiv](https://user-images.githubusercontent.com/79310839/108498959-e4e42e00-72ad-11eb-980e-f25c59efc081.PNG)

Im Beispiel wird keiner dieser im code-Element angeführt. **Soll einer/mehere dieser Codes für die Ressource verwendet werden, und wenn ja, welche(r)?**

**Comment by cerbelding** [comment]
Die Beispiele sind lediglich mögliche Umsetzungen. Ideal ist immer möglichst viele Codes, auch aus verschiedenen Codesystemen zu nutzen.

Ihr Screenshot beschreibt auch nur einen Ausschnitt der durch das ValueSet erlaubten Codes.
Darüber hinaus sind auch noch valide:
* Include codes from Icd-10-gm where concept IsA B23
* Include codes from SNOMED_CT where concept IsA 86406008

**Comment by riejo** [comment]
Die Frage ist, wer entscheidet, auf welchen Code sich festgelegt wird? Oder ist es "egal", welcher von diesen verwendet wird, und jeder regelt das für sich selbst?

**Comment by julsas** [comment]
Wenn man nur die Information 'HIV-Infektion' hat, würde ich auf SNOMED 86406008 und ICD B24 gehen. Egal ist das nicht, sonst kodiert man evtl. Sachverhalte, die beim Patienten nicht vorliegen.

**Comment by riejo** [comment]
Dem stimme ich zu. Nur erschließt sich mir der Sinn hinter den anderen Codes (noch) nicht ganz. Nach meinem Verständnis dient die Condition nur zur Angabe, ob eine HIV-Infektion beim Patienten vorliegt oder nicht oder ob diese unbekannt ist. Die Beispiele lassen auch nur auf die allgemeine Präsenz und nicht auf das Beschreiben von weiteren Informationen deuten. Für die Angabe zu HIV gibt es nur die Antwortmöglichkeiten "ja", "nein" und "unbekannt". Von daher ist der Zweck der restlichen Codes des ICD-ValueSets für mich nicht klar gegeben.

**Comment by julsas** [comment]
Für den reinen EDC UseCase braucht man die anderen Codes wahrscheinlich nicht. Ein Grund die weiteren Codes aufzunehmen war, dass man auch sekundäre Datennutzung aus Routinedaten unterstützen möchte, wie in der MII.

**Comment by riejo** [comment]
Zum Verständnis, die ValueSets, welche u.a. die Diagnosen (nicht nur HIV) codieren, sind nicht nur speziell für den GECCO-Datensatz gedacht, sondern sollen auch für andere Zwecke verwendet werden?

**Comment by julsas** [comment]
Doch schon für GECCO, aber HIV-Patienten hab ich in den Routinedaten nicht allein unter B24. Eingabe mit EDC ist der eine UseCase. Wenn ich auf den Bestandsdaten suche, würde ich halt auch nach B22 usw. gucken.

**Comment by riejo** [comment]
Achso, also für das EDC-System ist lediglich der B24 vorgesehen, bei den Bestandsdaten werden alle Codes aus dem ValueSet berücksichtigt?

**Comment by julsas** [comment]
> Achso, also für das EDC-System ist lediglich der B24 vorgesehen, bei den Bestandsdaten werden alle Codes aus dem ValueSet berücksichtigt? 

Das war die Intention, ja.

**Comment by riejo** [comment]
Ok, gut. Danke für die Aufklärung!
