### ISSUE TITLE
Datumswerte mit Patientenbezug

### ISSUE THREAD

**Issue by chrmey** [hl7germany/forschungsnetz-covid19#112]
Während der Konfiguration der automatischen Pseudonymisierung/Anonymisierung der Ressourcen ist mir folgendes aufgefallen. 

Wir orientieren uns bei der de-identification der Ressourcen an HIPAA Safe-Harbor. Dort steht folgendes: 

>Dates associated with test measures, such as those derived from a laboratory report, are directly related to a specific individual and relate to the provision of health care. Such dates are protected health information.  As a result, no element of a date (except as described in 3.3. above) may be reported to adhere to Safe Harbor. 

Quelle: https://www.hhs.gov/hipaa/for-professionals/privacy/special-topics/de-identification/index.html#dates

Danach würden wir alle Datumswerte die in Patientenbezug stehen (alle in GECCO) auf das Jahr generalisieren. Das Problem was ich damit habe ist, dass dies potentiell die Interoperabilität gefährdet. Das überwiegt meines Erachtens aber nicht den Datenschutz des Patienten.  

Wie damit umgegangen werden soll bzw. soetwas später verwertet wird ist natürlich eher Angelegenheit des Anwendungsfalles, aber vielleicht gibt es ja hier schon eine Meinung dazu.

**Comment by julsas** [comment]
Die Frage muss auf CODEX-Ebene geklärt werden. Die FHIR-Profile benötigen Zeitstempel. Wenn diese entfernt werden, geht der zeitliche Kontext verloren.

**Comment by chrmey** [comment]
Das sehe ich auch so. Bestenfalls muss eine Methode zur Pseudonymisierung gefunden werden, die die Zeitwerte verfälscht, aber die Zeitfolge identisch hält.

**Comment by julsas** [comment]
Im NUM-Knoten v2 ist die Pseudonymisierung, wo das geregelt ist oder?

**Comment by chrmey** [comment]
Genau
