### ISSUE TITLE
ValueSets in Medikation

### ISSUE THREAD

**Issue by chrmey** [hl7germany/forschungsnetz-covid19#114]
Die zweite Frage in Issue #53 ist noch nicht beantwortet. Wo liegen die Unterschiede der einzelnen Kategorien bei den doppelten Elementen?

**Comment by julsas** [comment]
Die Unterschiede der Kategorien sind ATC spezifisch. Wirkstoffe werden nach dem Organ oder Organsystem, auf das sie einwirken, und nach ihren chemischen, pharmakologischen und therapeutischen Eigenschaften in verschiedene Gruppen eingeteilt. Beispiel Ivermectin im ATC als Tablette und Creme.
