### ISSUE TITLE
Canonical URL von MI-I Diagnose ist doppelt vergeben

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/forschungsnetz-covid19#12]
Abhängig vom Ausgang von https://chat.fhir.org/#narrow/stream/179307-german.2Fmi-initiative/topic/.5BDIAGNOSE.5D.20doppelte.20Canonical.20URL muss ggf. die Canonical URL in den abgeleiteten Profilen angepasst werden

**Comment by alexzautke** [comment]
Fixed im Modul Diagnose, Dependencies wurden geupdatet.
