### ISSUE TITLE
Problem beim Validieren von Codes der ValueSet

### ISSUE THREAD

**Issue by riejo** [hl7germany/forschungsnetz-covid19#120]
Beim Suchen von Bestandsdaten für den GECCO-Datensatz sind wir auf folgendes gestoßen. Wir lassen uns dabei einen großen Datensatz mit Diagnosen und Prozeduren ausgeben und, falls unter diesen ein Code aus einem der ValueSets gefunden wird, wird die entsprechende Ressource erstellt. Nur ist das Problem, dass das Validieren der Codes fehlschlägt. 
Die ValueSets sind teilweise über Filter definiert:

<img width="333" alt="valueset_filter" src="https://user-images.githubusercontent.com/79310839/120613124-375ceb00-c456-11eb-8972-6ae866dd3873.PNG">

Für das Validieren arbeiten wir mit folgender Operation: https://www.hl7.org/fhir/valueset-operation-validate-code.html. Bei unserem vorrübergehenden Test-FHIR-Server funktioniert diese einwandfrei bei ValueSets, in welchen das Filter-Elelement nicht auftritt, bei ValueSets mit Filter kommt folgende Fehlermeldung:

<img width="261" alt="vonk_fehler" src="https://user-images.githubusercontent.com/79310839/120613159-3fb52600-c456-11eb-94bd-b5965e2f5165.PNG">

Auch bei Validator von Simplifier stößt man auch auf eine dementsprechende Warnung, dass dies nicht möglich sei:

<img width="857" alt="simplifier_fehler" src="https://user-images.githubusercontent.com/79310839/120613187-46439d80-c456-11eb-985e-225ab9ed7bed.PNG">

Anscheinend können beide Dienste nicht mit den in den ValueSet definierten Filtern umgehen.
Diese Problematik behindert uns ungemein, da wir dadurch nicht wirklich prüfen können, ob ein Code zu einem ValueSet gehört oder nicht.
Daher die Frage: Wurde das Validieren von Codes der ValueSets schon getestet, bzw. wie und mit welchen Dienst(en)? Oder wäre es möglich, die ValueSets so zu gestalten, dass auch andere Dienste mit denen umgehen können? Also dass die dazugehörigen Codes in den ValueSets explizit aufgezählt werden?

**Comment by julsas** [comment]
Hallo @riejo, ja der Simplifer-interne Validator hat nur eingeschränkten Terminologie-Support. 
Der Ontoserver kann mit den Filtern umgehen. @cdrenkhahn

**Comment by riejo** [comment]
Hallo @julsas, vielen Dank für die Info!
