### ISSUE TITLE
DiagnosisCovid19 is missing system in patternCoding in Condition.code.coding:sct element

### ISSUE THREAD

**Issue by geloro94** [hl7germany/forschungsnetz-covid19#121]
The Profile Profile-Condition-DiagnosisCovid19 is missing the system information in the patternCoding of Condition.code.coding.sct:
```json
"id": "Condition.code.coding:sct",
"path": "Condition.code.coding",
"sliceName": "sct",
"min": 1,
"patternCoding": {
     "code": "840539006",
}
```
Should be:
```json
"id": "Condition.code.coding:sct",
"path": "Condition.code.coding",
"sliceName": "sct",
"min": 1,
"patternCoding": {
  "code": "840539006",
  "system": "http://snomed.info/sct"
}
```

**Comment by julsas** [comment]
Hi @geloro94, thanks for checking. The system information should be present through the underlying MII-Diagnose baseDefinition that sets the system pattern. Here the differential extends on top of that. Is this causing any issues for you when validating against the profile? I checked the snapshot and it looks like it's building correctly with code and system inside patternCoding.

**Comment by geloro94** [comment]
Hello, sorry for my late reply, you are absolutely right, the error was on my side.
