### ISSUE TITLE
Symptom "Rigor" falsch übersetzt?

### ISSUE THREAD

**Issue by RiepenSa** [hl7germany/forschungsnetz-covid19#126]
Hallo,
im simplifier ist "Rigor" bei den Symptomen mit "Starre" übersetzt. Das trifft die Bedeutung des Codes eigentlich nicht. Es handelt sich bei Rigor mit SNOMED CT Code 38880002 um eine schwere Form von Schüttelfrost (Parent-Begriff bei SNOMED CT Shivering or Rigors 248456009; assoziierter UMLS-Code C0424790 "Rigor - Temperature associated observation", mit Schüttelfrost als Synonym aus dem deutschen MedDRA).
Für das deutsche "Rigor" - im Sinne einer Muskelsteifigkeit, wie sie z.B. bei der Parkinson-Erkrankung auftritt, - würde Muscle Rigidity (SNOMED CT Code 16046003) passen, sollte doch Starre gemeint sein.
Viele Grüße
Sarah Riepenhausen (IMI Münster)

**Comment by julsas** [comment]
Hallo @RiepenSa, 
der Code stammt aus der Liste der Symptome von SNOMED: https://confluence.ihtsdotools.org/display/FHIR/COVID-19+Symptoms+Present 
Die Mediziner*innen hier schlagen vor, "Rigoren" als Übersetzung zu verwenden.

**Comment by julsas** [comment]
43724002 |Chill (finding)| haben wir schon mit Schüttelfrost übersetzt.

**Comment by RiepenSa** [comment]
Ich weiß, dass Chills schon mit Schüttelfrost übersetzt wurde. Allerdings tut sich die deutsche Sprache glaube ich schwer damit das zu trennen und mit der Angabe von Severity ist es sogar irgendwie gedoppelt: Severe Chills sind ja Rigors.
"Rigoren" ist mir während meines Medizinstudiums nicht über den Weg gelaufen, muss ich sagen, daher weiß ich nicht wie verbreitet der Begriff tatsächlich ist.
HPO definiert Chills als "sudden feeling of cold", Rigors als "severe chills with violent shivering". Andere Terminologien führen aber schon auch ein Zittern/Shivering für Chills auf. Aber vielleicht angelehnt an HPO "Chills" eher als "Plötzliches Kältegefühl" (mit ggf. leichtem Zittern) und "Rigor" als voll ausgeprägten "Schüttelfrost"?

**Comment by julsas** [comment]
Ok! Dann ändern wir:

- Chills -> Plötzliches Kältegefühl
- Rigor -> Schüttelfrost
