### ISSUE TITLE
SNOMED Code im Profil "Body height" existiert nicht

### ISSUE THREAD

**Issue by riejo** [hl7germany/forschungsnetz-covid19#128]
Im Profil zur "Body height" wird der SNOMED Code "248334005" angegeben:

            {
                "id": "Observation.code.coding:snomed",
                "path": "Observation.code.coding",
                "sliceName": "snomed",
                "min": 0,
                "max": "*",
                "patternCoding": {
                    "system": "http://snomed.info/sct",
                    "code": "248334005"
                }
            }

Dieser ist jedoch über den SNOMED Browser nicht auffindbar.

![BEWEIS BODY HEIGHT NICHT EXISTENT](https://user-images.githubusercontent.com/79310839/132852558-597af83d-4244-4594-a1c5-fbeeacd9a17a.PNG)

**Comment by cerbelding** [comment]
Der SNOMED-Code `248334005` wurde mit der "SNOMED CT July 2021 International Edition" deaktiviert, da eine umfangreiche Re-Modellierung erfolgt ist.
Siehe Release-Notes: https://confluence.ihtsdotools.org/display/RMT/SNOMED+CT+July+2021+International+Edition+-+SNOMED+International+Release+notes

Der neue Code wäre dann `1153637007 |Body height (observable entity)|`


In der [MIO Beschreibung der KBV](https://mio.kbv.de/pages/viewpage.action?pageId=43254076) und in [Bioportal](https://bioportal.bioontology.org/ontologies/SNOMEDCT?p=classes&conceptid=248334005) ist der Code aber noch zu finden.
