### ISSUE TITLE
History of Organ Recipient - SCT Code not valid in value set

### ISSUE THREAD

**Issue by chrmey** [hl7germany/forschungsnetz-covid19#129]
In https://simplifier.net/forschungsnetzcovid-19/organrecipient -> coding.code.sct there is a fixed value on code 161663000 with a binding on value set ValueSetSNOMEDDiagnoseCodes. However the value set does not include the code 161663000, so the validation fails.

**Comment by julsas** [comment]
@chrmey ValueSetSNOMEDDiagnoseCodes includes codes from SNOMED_CT where concept IsA 243796009 und 161663000 is-a subtype of 243796009. Sollte daher in der VS Expansion enthalten sein.

**Comment by chrmey** [comment]
Stimmt, falsch nachgeschaut. Danke!
