### ISSUE TITLE
Patient Resource Extensions

### ISSUE THREAD

**Issue by chrmey** [hl7germany/forschungsnetz-covid19#131]
Die Extensions Age und Ethnic Group für die Patient Ressource machen uns leider aktuell große Probleme, die eventuell auch andere Standorte teilen könnten. Unser FHIR-Server ist direkt am PIX angebunden, wodurch die Patient-Ressource regelmäßig aktualisiert wird. Dabei werden die Extensions überschrieben, außerdem können wir diese Extension immer nur über ein Patch in die Patient Ressource einfügen, was auch schwierig ist. Um die (bereits komplexe) Implementierung von Mappings auf den GECCO-Datensatz etwas zu vereinfachen, würden wir gerne diesen Vorschlag machen. Statt den Extensions, könnten einfache Observations verwendet werden, die Age und Ethnical Group abbilden. Dadurch werden Berechtigungs-/Interessenkonflikte an der Patient Ressource umgangen und die Implementierung  des Datensatzes vereinfacht.

**Comment by julsas** [comment]
@chrmey setze ich gerne um. Wie bekommen wir Konsens der Standorte für die Änderung?

**Comment by chrmey** [comment]
@julsas Ich glaube der beste Weg wäre über den AP6 CODEX JF. Ich würde das vorab mal mit ODM2FHIR klären.

**Comment by chrmey** [comment]
@julsas Wir lassen das erstmal aus. Wir haben jetzt einen Workaround gebaut, sodass wir lokal keine Probleme mehr haben. Eventuell sollte das Thema aber in einer kommenden Revision berücksichtigt werden.
