### ISSUE TITLE
Vital signs -> SpO2

### ISSUE THREAD

**Issue by chrmey** [hl7germany/forschungsnetz-covid19#132]
https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Peripheraloxygensaturation enthält ein Pattern in Code.coding, welches einen bestimmten LOINC Code fordert. Damit ist die Observation dann nur zur Verwendung im Rahmen von BGAs bzw. Gas Panels nutzbar. Die Pulsoximetrie auf der ITS fällt mit diesem Coding raus. 

Im Art-Decor findet sich für dieses Profil noch der Code 59408-5, mit dem sich die Pulsoximetrie abbilden lässt. Kann dieser wieder eingebaut werden?

**Comment by julsas** [comment]
@chrmey Ihr könnt da ein weiteres LOINC Coding für den ITS Use Case hinzufügen und beide Codes nebeneinander haben.

**Comment by chrmey** [comment]
@julsas Also einfach ein weiteres Coding Element einfügen?

**Comment by julsas** [comment]
Genau mit dem `2708-6 Oxygen saturation in Arterial blood` ist man konform zu FHIR Core, FHIR DE Basis, KBV etc. und das weitere Coding hat dann zusätzlich die Pulsoximetrie Information.
