### ISSUE TITLE
Falsches Profil im GECCO 1.0.5 package auf Simplifier

### ISSUE THREAD

**Issue by riejo** [hl7germany/forschungsnetz-covid19#134]
Im Package für GECCO 1.0.5 auf Simplifier ist für das Profil 'History of Organ Recipient' bei dem coding für ICD-10 unter system die falsche URL als Fixed Value angegeben. Diese lautet noch 'http://fhir.de/CodeSystem/dimdi/icd-10-gm', wobei im Coding-Profil für ICD-10-GM die URL mittlerweile als 'http://fhir.de/CodeSystem/bfarm/icd-10-gm' festgelegt ist. Dies sorgt für Validierungsfehler, wenn die aktuelle URL verwendet wird, auch beim Simplifier Validator. 

<img width="860" alt="Unbenannt" src="https://user-images.githubusercontent.com/79310839/157022694-a05950bd-f17a-472d-ab15-e0ec7d6d0fd1.PNG">

Für 'History of Organ Recipient' gibt es schon die Version 1.0.5, in welchem dies richtig vermerkt ist. Im Package befindet sich noch die Version 1.0, eventuell müsste dies ausgetauscht werden.

**Comment by julsas** [comment]
@riejo ja, das benötigt ein neues Package Release. Rückwirkend kann das in 1.0.5 nicht getauscht werden.

**Comment by riejo** [comment]
@julsas, alles klar, danke für die Rückmeldung.
