### ISSUE TITLE
Patient in Beispiel GECCO Bundle nicht valide Bundle.entry[0].resource.ofType(Patient).extension[0].value.ofType(Coding)

### ISSUE THREAD

**Issue by hhund** [hl7germany/forschungsnetz-covid19#139]
Die Patienten Ressource im Beispiel Bundle [GECCO_bundle_short.json](https://github.com/hl7germany/forschungsnetz-covid19/blob/384d49a3ffec6f634ebc35100f279c213710031b/beispiele/GECCO_bundle_short.json) ist nicht valide:

```
Error (Bundle.entry[0].resource.ofType(Patient).extension[0].value.ofType(Coding), Line 1, Col 646): 
Konnte nicht bestätigen, dass die angegebenen Codes im ValueSet https://www.netzwerk-universitaetsmedizin.de/fhir/ValueSet/ethnic-groups enthalten sind, und ein Code aus diesem ValueSet ist erforderlich
Info (Bundle.entry[0].resource.ofType(Patient).identifier[0], Line 1, Col 1204): 
Dieses Element stimmt mit keinem bekannten Slice defined in the profile https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/Patient überein.
```

Siehe:
https://github.com/hl7germany/forschungsnetz-covid19/blob/384d49a3ffec6f634ebc35100f279c213710031b/beispiele/GECCO_bundle_short.json#L23-L30

Im ValueSet https://www.netzwerk-universitaetsmedizin.de/fhir/ValueSet/ethnic-group ist enthalten:
```
{
  "system": "http://snomed.info/sct",
  "code": "26242008",
  "display": "Mixed (qualifier value)"
}
```

Wobei zu diskutieren wäre, ob `26242008` teil dieses ValueSets sein darf, da die Semantik des Codes (`qualifier value`), aka. ein Adjektiv, hier eigentlich nicht passt.

**Comment by julsas** [comment]
Fixed [89c0115](https://github.com/hl7germany/forschungsnetz-covid19/commit/89c0115ace2be97775ba63a201dd9134b819424d)
