### ISSUE TITLE
Fehler beim Laden des Gecco-Pakets

### ISSUE THREAD

**Issue by jsbankole** [hl7germany/forschungsnetz-covid19#146]
Beim Laden des gecco Implementation Guides im hapifhir jpa Startprojekt (6.0.1) trat folgender Fehler auf:

`fhir-jpaserver-start | ca.uhn.fhir.jpa.packages.ImplementationGuideInstallationException: HAPI-1286: Error installing IG de.gecco#1.0.5: ca.uhn.fhir.jpa.packages.ImplementationGuideInstallationException: HAPI-1290: Failure when generating snapshot of StructureDefinition: StructureDefinition/gecco-condition-cardiovascular-diseases
hapi-fhir-jpaserver-start | at ca.uhn.fhir.jpa.packages.PackageInstallerSvcImpl.install(PackageInstallerSvcImpl.java:231)`

Der Server ist ein eigenständiger hapi-fhir-jpa Version 6.0.1 mit der folgenden Konfigurationsdatei application.yaml:
```
gecco:
  name: de.gecco
  version: 1.0.5
```

**Update**
Nachdem ich Patrick Werners Vorschlag in der Hapi-Chatgruppe gelesen hatte, funktionierte es bei mir folgendermaßen:
```
url: classpath:de.gecco-1.0.5.tgz
      name: de.gecco
      version: 1.0.5
```

**Comment by julsas** [comment]
@jsbankole guter Hinweis mit classpath. Ich habe bisher ein GitHub Repo genutzt in dem ich die Packages von Simplifier mit vorgenerierten Snapshots habe und von dort importiere. So z.B.:

```
gecco:
   url: https://github.com/julsas/mii-package-temp/raw/master/de.gecco-1.0.5.tgz
   name: de.gecco 
   version: 1.0.5
```
