### ISSUE TITLE
Covid Symptoms Binding falsche URL

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/forschungsnetz-covid19#17]
https://simplifier.net/ForschungsnetzCovid-19/SymptomsCovid19/~overview

Canonical im Binding "http://fhir.de/ValueSet/SARS-CoV-2-symptoms" löst nicht auf, muss "http://charite.de/ValueSet/SARS-CoV-2-symptoms" heißen

**Comment by julsas** [comment]
ist gefixt
