### ISSUE TITLE
Codesystem Frailty Score: Quelle, Übersetzung und Permission of Use

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/forschungsnetz-covid19#3]
[Clinical Frailty Scale](https://simplifier.net/forschungsnetzcovid-19/frailtyscore)

Das verwendete [ValueSet FrailtyScore](https://simplifier.net/ForschungsnetzCovid-19/frailty-score-duplicate-2) verwendet Codes aus [Codesystem Frailty Score](https://simplifier.net/ForschungsnetzCovid-19/frailty-score), welches laut seiner Canonical URL aus der Feder der Charité stammt.

Die angegebenen Werte stimmen jedoch mit der [Clinical Frailty Scale](https://www.dal.ca/sites/gmr/our-tools/clinical-frailty-scale.html) der Dalhousie University, Canada überein.

Für deren Verwendung ist eine "Permission of Use" erforderlich!

Die Canonical URL sollte international abgestimmt werden (evtl. HL7 Canada/Lloyd McKenzie oder die Universität direkt ansprechen)

Die Deutsche Übersetzung verwendet wiederholt den Begriff "frail".
Ist das im Mediziner-Sprech ein geläufiger Begriff?
Ich hätte das als ["gebrechlich"](https://de.wikipedia.org/wiki/Gebrechlichkeit) übersetzt.

**Comment by simoneOnFhir** [comment]
Laut [Clinical Frailty Scale©](https://www.dal.ca/sites/gmr/our-tools/clinical-frailty-scale/clinical-frailty-scale-translations.html#contentPar_text) ist Übersetzungen grundsätzlich ein Disclaimer hinzuzufügen!

**Comment by Kosmos3** [comment]
Eine Permission of Use wurde von der Dalhousie University erteilt. Die verwendete Übersetzung entspricht der Übersetzung der Deutsche Gesellschaft für Geriatrie e.V..
