### ISSUE TITLE
Risikofaktoren "other"

### ISSUE THREAD

**Issue by julsas** [hl7germany/forschungsnetz-covid19#32]
Um "other" abbilden zu können, müsste die binding strength für ICD/SCT extensible sein, das MII Diagnose Profil verlangt aber schon required.

**Comment by ByteGnome** [comment]
Ich spreche das Problem im Kümmerer-Team an. Sollte aber kein Problem sein, das Binding auf extensible zu setzen.

**Comment by julsas** [comment]
Haben für "other" jetzt jeweils intensionale Definitionen in die ValueSets eingebaut.
