### ISSUE TITLE
History of Travel - Yes/No/Unknown

### ISSUE THREAD

**Issue by corneliusknopp** [hl7germany/forschungsnetz-covid19#50]
https://simplifier.net/forschungsnetzcovid-19/historyoftravel

FHIR-Resource `HistoryOfTravel` ist auf Ort & Zeitspanne der Reise ausgelegt.
Das [Element in Art-Decor](https://art-decor.org/art-decor/decor-datasets--covid19f-?id=2.16.840.1.113883.3.1937.777.53.1.1&effectiveDate=2020-04-08T13%3A04%3A13&conceptId=2.16.840.1.113883.3.1937.777.53.2.1.2208&conceptEffectiveDate=2020-04-30T15%3A48%3A55&language=de-DE) bietet jedoch nur die Antwortmöglichkeiten "Ja", "Nein", "Unbekannt", jeweils als SNOMED qualifier value.

Wenn keine Reisekativität zum Patienten in FHIR angelegt ist, kann die Frage entweder mit Nein oder gar nicht beantwortet sein.

**Vorschlag:** Einführung einer `Component`, welche diese qualifier-values abbildet.  
```json
...
"component":  [
        {
            "code": {
                "coding":  [
                    {
                        "system": "http://loinc.org",
                        "code": "LL3044-6",
                        "display": "Yes/No/Unknown"
                    }
                ],
                "text": "Travel activity 14 days before symptoms begin"
            },
            "valueCodeableConcept": {
                "coding": [
		    {
			"system": "http://snomed.info/sct",
			"code": "373066001",
			"display": "Yes (qualifier value)"
		    }
		],
		"text": "There is a travel activity 14 days before symptoms begin"
	}
]
...
```

**Alternative, mittels HAPI FHIR Java-Client:**
```java
Observation.ObservationComponentComponent component = new Observation.ObservationComponentComponent()
                .setCode(new CodeableConcept()
                        .addCoding(new Coding().setSystem("http://loinc.org").setCode("LL3044-6").setDisplay("Yes/No/Unknown"))
                        .setText("Travel activity 14 days before symptoms begin"))
                .setValue(new CodeableConcept()
                        .addCoding(new Coding().setSystem("http://snomed.info/sct").setCode("373066001").setDisplay("Yes (qualifier value)"))
                        .setText("There is a travel activity 14 days before symptoms begin"));
observation.addComponent(component);
```

**Comment by julsas** [comment]
@corneliusknopp guter Hinweis. Vielleicht passt besser, Yes/No/Unknown in Observation.value[x] zu sagen und die Components mit den Reisedaten nur zu nutzen, wenn vorher "Yes" beantwortet wurde.
Bsp. Yes: https://simplifier.net/forschungsnetzcovid-19/observation-example-duplicate-67
Bsp. No: https://simplifier.net/forschungsnetzcovid-19/observation-example-duplicate-66

**Comment by corneliusknopp** [comment]
Das wäre natürlich noch besser. Dann müsste man den LOINC-Code für das Coding garnicht weiter mit angeben.

**Comment by julsas** [comment]
Ok ist auch hier angepasst: https://simplifier.net/forschungsnetzcovid-19/historyoftravel
