### ISSUE TITLE
Inkonsistenz bei Abfrage Medikation

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#53]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

Es besteht Inkonsistenz bei der Abfrage der Medikation:
- ACE-Hemmer, Immunoglobuline, Antikoagulation stehen nicht unter COVID-Therapie. 
Es ist unklar, ob hier die vorherige Medikation abgefragt wird, oder Medikation während COVID.

- Bei manchen Medikationen in 'COVID-Therapie', sind einige Kategorienbezeichnungen doppelt, aber mit verschiedenen Codes (e.g. Ivermectin). Unterschiede zwischen den Kategorien, sollten für die Dokumentare ersichtlich sein.

## further Information
/

## Contact
Frage gestellt von: ?
Ansprechpartner: S. Biergans (@sbiergans)

**Comment by julsas** [comment]
Gemäß Vorgaben handelt es sich bei ACE-Hemmern, Immunoglobulinen, Antikoagulation um die Vormedikation.

**Comment by chrmey** [comment]
Die zweite Frage ist hier noch nicht abschließend beantwortet. Dazu brauchen wir auch eine Auskunft wie wir hier vorgehen sollen.
