### ISSUE TITLE
Umsetzung Visitenstruktur

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#54]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

- Soll es eine Visitienstruktur geben, oder welche Werte sollen bei Labor-, Vitalparameter eingegeben werden (e.g. min, max)?
- Wenn Werte automatisch aus den Primärsystemen ausgelesen werden, wird es pro Patient mehrere Labor-, Vitalwerte geben.

## further Information
- aktuell ist es in REDCap so implementiert, dass sowohl für Laborwerte, Medikamente, Vitalwerte, Körpergröße-/Gewicht, Ergebnis Folgeabstrich und die Bildgebenden Verfahren keine Zeitpunkte erfasst werden können (Hinweis S.Schild)
- Eine Zeitangabe ist in art-decor nicht vorgesehen.
- Da die für GECCO definierten FHIR-Profile beispielsweise `recordedDate`, `performedDateTime` oder `effectiveDateTime` als mandatory Items beinhalten, muss hier eine Lösung gefunden werden. (Hinweis [C. Erbelding](https://github.com/cerbelding))
- Aktuell gibt es keine Zeitpunkte außer Geburts- & Impf-Datum (Hinweis [C. Erbelding](https://github.com/cerbelding))

## Contact
Frage gestellt von: ?
Ansprechpartner: S. Biergans (@sbiergans), C. Erbelding (@cerbelding)

**Comment by julsas** [comment]
- Angaben zu Visitenstrukturen werden im Rahmen von NAPKON geklärt.

- Da keine Visitenstruktur durch den Datensatz vorgegeben wird, muss ein Datum im EDC-System (RedCap/SecuTrial) dokumentiert werden.

**Comment by sbiergans** [comment]
>     * Angaben zu Visitenstrukturen werden im Rahmen von NAPKON geklärt.
> 
>     * Da keine Visitenstruktur durch den Datensatz vorgegeben wird, muss ein Datum im EDC-System (RedCap/SecuTrial) dokumentiert werden.

Aber außer NAPKON gibt es ja noch andere Studien, die mit den von uns bereitgestellten Daten arbeiten sollen. Die Datenbereitstellung soll doch unabhängig von einer speziellen Studien sein? Daher müsste schon definiert werden, was wir überhaupt bereitstellen sollen (e.g. alle Laborwerte, nur Max, nur Ersten?). Das ist, meiner Meinung nach, eine Grundsatzentscheidung, die vor Inbetriebnahme des NUM-Knotens getroffen werden muss.

**Comment by SylviaThun** [comment]
Das sollte in der jeweiligen Studie vorgegeben werden. Das gilt auch für alle anderen Studien.
