### ISSUE TITLE
SOFA Score

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#55]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

SOFA score - [art-decor Definition für SOFA](https://art-decor.org/art-decor/decor-datasets--covid19f-?id=2.16.840.1.113883.3.1937.777.53.1.1&effectiveDate=2020-04-08T13%3A04%3A13&conceptId=2.16.840.1.113883.3.1937.777.53.2.1.1690&conceptEffectiveDate=2020-04-08T00%3A00%3A00&language=de-DE) ist leer; wir haben uns an der [Simplifier-Definition](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/SOFA-Score2) orientiert, und alle einzelnen Parameter zur SOFA Berechnung hinzugefügt.

- Ist der Total score hier auch gewünscht?

   

## further Information
- Wir haben aktuell die Summe der Einzelscores umgesetzt, wobei nicht ausgefüllte Einzelscores derzeit für die Berechnung ignoriert werden (Hinweis [B. Sailer](https://github.com/b-sailer))
- Der Total Score wird im zugehörigen Paper ([DOI 10.1007/BF01709751](https://dx.doi.org/10.1007/BF01709751), S.708) als Summe der 6 Einzel-Scores berechnet (Hinweis [C. Erbelding](https://github.com/cerbelding))

## Contact
Frage gestellt von: ?
Ansprechpartner: S. Biergans (@sbiergans), B. Sailer (@b-sailer), C. Erbelding (@cerbelding)

**Comment by cerbelding** [comment]
@b-sailer

**Comment by SylviaThun** [comment]
Laut Redaktionsgruppe ist der Gesamtscore vorgesehen.
