### ISSUE TITLE
Einheiten bei Labor-/Vitalparameter

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#56]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

- Bei Laborparametern und manchen Vitalparametern werden aktuell nur die verschiedenen Einheiten abgefragt. 
- Das entspricht aber zum Teil mehreren LOINC codes pro Einheit (z.B. bei CRP), da hier zum Beispiel auch verschiedene Messmethoden kodiert sind. 

## further Information
- Wir werden es im eCRF jetzt aufschlüsseln, damit ein einzelner LOINC Code zugeordnet werden kann.

## Contact
Frage gestellt von: ?
Ansprechpartner: S. Biergans (@sbiergans)

**Comment by SylviaThun** [comment]
Vorgabe der LOINC Codes mit den zugeordneten Einheiten muss über das jeweilige Labor vorgeben werden.
