### ISSUE TITLE
Antwortmöglichkeit "Unbekannt"

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#57]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

- Wie geht man mit der Erfassung des Wertes „unknown“ um. 
- Hier könnte für eine weitere Spezifikation nach Auswahl des Wertes „unbekannt“, wieder eine weitere Auswahl aufklappen, in der der Grund für die Angabe angegeben werden soll (Patienten nicht danach gefragt, Patient verweigert Auskunft, technisches Problem, etc…).
- Ist so eine 2-fach Verschachtelung möglich: Leidet der/die Patient*in unter einer chronischen Lungenerkrankung? Ja, Asthma? unbekannt. Und anschließend eine Abfrage, wieso die Angabe unbekannt ist?

## further Information
- `Unbekannt` ist laut GECCO-Implementation-Guide in Simplifier in den meisten Fällen mit einer `uncertainty-of-presence`-Extension kodiert. [Beispiel: ganz unten](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Chroniclungdiseases) (Hinweis [C. Erbelding](https://github.com/cerbelding))

## Contact
Frage gestellt von: S. Schild
Ansprechpartner:  S. Schild, S. Biergans (@sbiergans)

**Comment by dagmarkrefting** [comment]
https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence
ist ein toter Link?

**Comment by cerbelding** [comment]
Das ist die Canonical-URL, wie sie im Simplifier eingetragen ist.


-------- Ursprüngliche Nachricht --------
Von: Dagmar Krefting <notifications@github.com>
Datum: 19.11.20 21:24 (GMT+01:00)
An: hl7germany/forschungsnetz-covid19 <forschungsnetz-covid19@noreply.github.com>
Cc: Cornelius Erbelding <cornelius.erbelding@outlook.de>, Author <author@noreply.github.com>
Betreff: Re: [hl7germany/forschungsnetz-covid19] Antwortmöglichkeit "Unbekannt" (#57)


https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.netzwerk-universitaetsmedizin.de%2Ffhir%2FStructureDefinition%2Funcertainty-of-presence&data=04%7C01%7C%7C21516ba2e0144f47acea08d88cc926fd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637414142845850123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IJKp5pDNPhUDl0h3zmvAH6YNorDkpg5rpJOHCXcpO80%3D&reserved=0>
ist ein toter Link?

**Comment by SylviaThun** [comment]
Keine Unterteilung von unknown vorgesehen gemäß Redaktionsgruppenbeschluss.
