### ISSUE TITLE
Vorschlag zur Einheiten-Harmonisierung

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#58]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgender Vorschlag aufgekommen:

Vorschlag zur Festlegung der Einheiten, in der die Werte erfasst werden sollen (v.a. Laborwerte): 
- aus der Erfahrung mit anderen Datenprojekten hat sich gezeigt, dass es oftmals für weniger Probleme in der Datenauswertung sorgt, wenn für die zu liefernden Daten eine einheitliche Einheit vorgeben wird. 
- Sprich, sofern sich die erfassten Werte am jeweiligen Standort auf die entsprechende Einheit umrechnen lassen, ist das ggf. einfacher, als dies in einem weiteren Nachbearbeitungsschritt am Auswertestandort durchzuführen.

## further Information
- Aktuell wird in GECCO explizit nach verschiedenen Einheiten differenziert, bzw. verschiedene LOINC codes pro Analyt sind möglich. 
- Dies wäre eine Entscheidung, die das Redaktionsteam treffen muss. 

## Contact
Vorschlag von: S. Schild
Ansprechpartner: S. Schild, S. Biergans (@sbiergans)

**Comment by SylviaThun** [comment]
Einheiten und Zuordnungen zu LOINC werden von den jeweiligen Laboren vorgegeben.
