### ISSUE TITLE
Konzepte-Mix "Entlassstatus"

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#59]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

- Wie man an den SNOMED Codes schon erkennen kann, wurden da zwei verschiedene Konzepte durcheinander gewürfelt: Der Zustand des Patienten (`alive`, `dead`) und Prozeduren (`Hospital admission`, `Patient referral`, `Referral to alliative care service`). 
- Was soll denn ausgewählt werden, wenn der Patient lebend in ein Krankenhaus eingewiesen wurde? 
- Auch innerhalb der Prozeduren gibt es Überschneidungen: ich kann einen Patienten durchaus zur palliativen Behandlung in ein anderes Krankenhaus überführen. Was wählt man dann aus?

## further Information
SNOMED Codes:

| RESPONSE OPTIONS | Observation.value[x].coding |
| -- | -- |
| Alive | `371827001 \|Patient discharged alive (finding)\|` |
| Admission to hospital | `32485007 \|Hospital admission (procedure)\|` |
| Referral to other institution | `3457005 \|Patient referral (procedure)\|` |
| Death | `419099009 \|Dead (finding)\|` |
| Palliative discharge | `306237005 \|Referral to palliative care service (procedure)\|` |
| Unknown | `261665006 \|Unknown (qualifier value)\|` |

## Contact
Frage gestellt von: O. Heinze
Ansprechpartner: O. Heinze, S. Biergans (@sbiergans)

**Comment by cerbelding** [comment]
**Possibly related to Issue #42**

**Comment by SylviaThun** [comment]
Der Einwand ist korrekt. Derzeit gibt es in SNOMED keine bessere Lösung, daher wird eine Lösung mit SNOMED Int abgeklärt. Die Problematik ist im KDS Fall ähnlich.
