### ISSUE TITLE
Condition Profile zusammenführen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/forschungsnetz-covid19#6]
Die Unterteilung der verschiedenen Conditions in unterschiedliche Profile ist nicht schlüssig.
Woran sollte ein Validator entscheiden können, gegen welches Profile eine Condition-Instanz zu validieren sei?

Es muss doch lediglich geprüft werden, ob es sich bei dem SNOMED/ICD-10-Code um eine COVID-relevante Diagnose handelt, oder nicht. Dafür alle sieben Profile "anprobieren" zu müssen, bis eines passt wäre sehr inperformant.

Einfacher wäre es, *ein* Profil mit Binding an die Liste der relevanten ICD-10/SNOMED-Codes zu definieren, um damit relevante von irrelevanten Diagnosen zu trennen.

Die Unterscheidung macht nur Sinn, wenn die Instanzen unterscheidbar wären, beispielsweise durch einen fixed value in Condition.category.

**Comment by patrick-werner** [comment]
Condition Profile die nur code definieren:
Cardiovascular Diseases
Chronic Kidney Diseases
Chronic Liver Diseases
Chronic Lung Diseases
Chronic Neurological or Mental Diseases
Complications of Covid-19
Diabetes Mellitus
Gastrointestinal Ulcers
Human Immunodeficiency Virus Infection
Malignant Neoplastic Disease
Rheumatological Immunological Diseases

diese sollte man zusammenfassen als covid19-base-condition o.ä.

Spezifische Profile:
Diagnosis Covid-19 (stage)
Organ Recipient (bodysite)

Könnten von covid19-base-condition abgeleitet sein.

**Comment by simoneOnFhir** [comment]
Lösung: meta auf 1..1 setzen mit fixed value pro Profil

**Comment by julsas** [comment]
Wir bleiben bei unterschiedlichen Profilen. Base-condition ist das MII-Diagnose-Profil.

**Comment by ByteGnome** [comment]
Grund: Für die unterschiedlichen Krankheitsgruppen (Bsp. [ChronicLiverDiseases](https://simplifier.net/forschungsnetzcovid-19/chronicliverdiseases)) gibt es jeweils ein festes vs. Das gemeinsame Glied ist (wie von @julsas erwähnt) das [MII-Diagnose-Profil](https://simplifier.net/medizininformatikinitiative-moduldiagnosen/diagnose-duplicate-3).

**Comment by ByteGnome** [comment]
Darf das Issue hier eig wieder geschlossen werden? Oder gibt es weitere Diskussionspunkte? (Könnten auch im Zulip drüber diskutieren, ist ja schon etwas schneller als hierüber ;D )

**Comment by simoneOnFhir** [comment]
https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/Umgang.20mit.20Profilen

**Comment by julsas** [comment]
sind jetzt Kategorien vergeben und meta wieder 0..1

**Comment by julsas** [comment]
Condition Profile zusammengeführt und von Base Condition basierend auf MII abgeleitet
