### ISSUE TITLE
Validitäts-Checks

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#60]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

- Sind Validitätschecks geplant? So wie ich das sehe, gibt es noch keine, oder?

## further Information
- Es sind aktuell in art-decor keine required/optional Variablen definiert und auch keine Ranges für einzelne Werte (z.B. Laborwerte). 
- In Simplifier sind allerdings mandatory Items angegeben! (zu erkennen an der 1..1 oder 1..* Relation)

## Contact
Frage gestellt von: S. Helfer 
Ansprechpartner: S. Helfer, S. Biergans (@sbiergans)

**Comment by SylviaThun** [comment]
Checks werden gemäß der Vorgaben in NAPKON umgesetzt und nicht in GECCO.
