### ISSUE TITLE
verwendete Codesysteme

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#61]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

- In Art-Decor wird als Codesystem für ICD-10 `1.2.276.0.76.5.409` angegeben, was ICD-10 GM Version 2012 entspricht: 
  - Warum wird hier keine aktuelle(re) Version verwendet, so wie sie auch in der regulären klinischen Kontext zur Anwendung kommt?
- Ebenfalls wird als Codesystem für SNOMED-CT nur SNOMED Clinical Terms angegeben, ohne jegliche Referenz zur verwendeten Version oder OID:
  - Welche Version wird verwendet? Sind hier nicht z.B. die im März eingeführten Codes ebenfalls relevant?

## further Information
- ICD-10 Codes für COVID-19 (U07.1! - U07.4!) sind in der angegebenen ICD-10 Version 2012 noch nicht vorhanden. (Hinweis [C. Erbelding](https://github.com/cerbelding))

## Contact
Frage gestellt von: [H. Stenzhorn](https://github.com/holger-stenzhorn)
Ansprechpartner: H. Stenzhorn (@holger-stenzhorn), S. Biergans (@sbiergans)

**Comment by cerbelding** [comment]
@holger-stenzhorn

**Comment by cerbelding** [comment]
@holger-stenzhorn

**Comment by SylviaThun** [comment]
Der Hinweis ist korrekt. Da die OID in der FHIR Umsetzung nicht genutzt wird, ist die OID aus ART DECOR nicht relevant. Wir überprüfen trotzdem diesen Punkt. 
Die OID .96 von SNOMED bleibt immer gleich. Die Versionierung erfolgt über die URI.

**Comment by SylviaThun** [comment]
Es soll immer die aktuelle Version von ICD-10-GM genutzt werden, somit sind auch die unterjährigen COVID-Codes vorhanden.
