### ISSUE TITLE
Geburtsdatum

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#62]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

- Das komplette Geburtsdatum könnte ein Datenschutzproblem werden. Wie könnte man das lösen?
- Das Geburtsdatum ist neben den Impfzeitpunkten das einzige absolute Datum im ganzen Datensatz, das wirkt irgendwie seltsam. 
Eigentlich würde man doch in relativen Datumsangaben rechnen (`Aufnahme + x Tage` für Laborwerte etc. oder` Aufnahme - x Jahre` für Impfungen). 
Wie ist das gedacht?

## further Information
- Es werden außer dem Geburts- und Impfdatum keine weiteren Daten abgefragt (insbesondere kein Aufnahmedatum)

## Contact
Frage gestellt von: S. Helfer
Ansprechpartner: S. Helfer, S. Biergans (@sbiergans)

**Comment by SylviaThun** [comment]
Das Geburtsdatum ist optional. Daher tritt kein Datenschutzprobleme auf.
