### ISSUE TITLE
Medikation: Dauer & Dosis

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#63]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

Das Medikations-Profil in FHIR bietet auch die Möglichkeit, Dauer und Dosis anzugeben. 
- Das wird in Art-Decor und damit auch REDCap nicht abgebildet. 
- Damit wird diese Information auch nicht geliefert

## Contact
Frage gestellt von: S. Helfer
Ansprechpartner: S. Helfer, [S. Biergans](https://github.com/sbiergans) (@sbiergans)

**Comment by cerbelding** [comment]
**Related to Issue #75**

**Comment by SylviaThun** [comment]
Sofern das Studiendesign dieses erfordert, sind Dosierungsangaben möglich. Diese können dann an die Meditation-Ressource weitergegeben werden.
