### ISSUE TITLE
Respiratorisches Outcome

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#64]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

Für die Frage nach dem respiratorischen Outcome ist nur die Antwortmöglichkeit "Beatmet: Ja/Nein" anzugeben. 
- Genau genommen ist damit die reine O2-Gabe nicht abgedeckt. Diese ist aber durchaus relevant. 
- Wird das noch angepasst?

## Contact
Frage gestellt von: S. Helfer
Ansprechpartner: S. Helfer, S. Biergans (@sbiergans)

**Comment by cerbelding** [comment]
Sollen die Zusatzinformationen zur Art der Beatmung aus dem Item `Therapie: Beatmung` kommen?
Damit bestünde Zusammenhang mit Issue #76.

**Comment by SylviaThun** [comment]
Die O2-Gabe wurde von dem Redaktionsteam nicht als relevant für den GECCO-Kern angesehen.
