### ISSUE TITLE
Alter: Berechnung

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#65]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

- Das Alter sollte automatisch berechnet werden anhand des Einschlussdatums. 
- Das spart Zeit und vermeidet Rechenfehler. 

## further Information
- im Datensatz gibt es aktuell kein Einschlussdatum, mit dem das Alter berechnet werden könnte

## Contact
Frage gestellt von: S. Schild
Ansprechpartner: S. Schild, S. Biergans (@sbiergans)

**Comment by cerbelding** [comment]
**Somehow related to Issue #68**

**Comment by SylviaThun** [comment]
Altersberechnung erfolgt über eCTD-Tool und nicht über Schnittstellenvorgaben.
Ein Datum ist in der Alter-Extension vorhanden: Time of Documentation
