### ISSUE TITLE
Record-Linkage

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#66]
## Description
Im Rahmen der Entwicklung eines DataDictionary für REDCap (NUM AP2) ist folgende Unklarheit aufgekommen:

- Wie genau funktioniert denn die Zuordnung von Daten und Patient?
- Soll die Patienten-ID/das Pseudonym im eCRF erfasst werden? 
- Oder läuft die Zuordnung unabhängig von den EDC-Systemen (bzw. nur über die Record-ID)?

## further Information
- aktuell wurde (eigenmächtig) ein Freitext-Feld `PatientID` zum DataDictionary hinzugefügt.

## Contact
Frage gestellt von: [B. Sailer](https://github.com/b-sailer)
Ansprechpartner: B. Sailer (@b-sailer), S. Biergans (@sbiergans)

**Comment by cerbelding** [comment]
@b-sailer

**Comment by SylviaThun** [comment]
Implementierungen vor Ort regeln den Namensraum.
