### ISSUE TITLE
Demographie: Alter

### ISSUE THREAD

**Issue by sbiergans** [hl7germany/forschungsnetz-covid19#68]
### **Description**

Im Rahmen der Testung des DataDictionary für REDCap durch ein Ärzte-Team in Erlangen ist folgende Unklarheit aufgekommen:

- Alter bei Studieneinschluss in Jahren oder Monat: Da keine Einheit angegeben werden kann, sorgt dies für unterschiedlich auszuwertende Zahlenwerte im gleichen Feld.
### 
### **further Information**

- im Datensatz wird nicht danach gefragt, ob das Alter in Jahren oder Monaten angegeben wird.

### **Contact**

Frage gestellt von: S. Schild
Ansprechpartner: S. Schild, S. Biergans

**Comment by SylviaThun** [comment]
Age in FHIR hat einen eigenen Datentyp mit UCUM Valueset. Daher ist die Einheit klar.
