### ISSUE TITLE
Laborwerte: Antikörper

### ISSUE THREAD

**Issue by sbiergans** [hl7germany/forschungsnetz-covid19#69]
### **Description**

Im Rahmen der Testung des DataDictionary für REDCap durch ein Ärzte-Team in Erlangen ist folgende Unklarheit aufgekommen:

- Laborwerte – Antikörper: Die Abkürzungen (QI, Qn) sind nicht verständlich.

### **further Information**

- In ArtDecor sind die Antikörper mit QI und Qn benannt.

### **Contact**

Frage gestellt von: S. Schild
Ansprechpartner: S. Schild, S. Biergans

**Comment by SylviaThun** [comment]
LOINC kennt quantitative und qualitative Messungen. Beides ist möglich.
