### ISSUE TITLE
Vitalparameter: Kohlendioxidpartialdruck / Sauerstoffpartialdruck

### ISSUE THREAD

**Issue by sbiergans** [hl7germany/forschungsnetz-covid19#70]
### **Description**

Im Rahmen der Testung des DataDictionary für REDCap durch ein Ärzte Team in Erlangen ist folgende Unklarheit aufgekommen:

- Es wäre sinnvoll, wenn man arteriell/ venös / kapillär dazu auswählen könnte.

### **Contact**

Frage gestellt von: S. Schild
Ansprechpartner: S. Schild, S. Biergans

**Comment by SylviaThun** [comment]
Ist auswählbar über den jeweiligen LOINC-Codes.
