### ISSUE TITLE
Krankheitsbeginn: Erkrankungsphase zum Zeitpunkt der COVID-19 Diagnose

### ISSUE THREAD

**Issue by sbiergans** [hl7germany/forschungsnetz-covid19#71]
### **Description**

Im Rahmen der Testung des DataDictionary für REDCap durch ein Ärzteteam in Erlangen ist folgende Unklarheit aufgekommen:

- Phase ohne Komplikationen/ mit Komplikationen, Kritische Phase: hier ist unklar welche Kriterien jeweils Komplikationen und welche der kritischen Phase entsprechen. Hier sind Beispiele/Hinweise sinnvoll, damit die Dateneingabe an allen Standorten einheitlich erfolgt.

### **Contact**

Frage gestellt von: S. Schild
Ansprechpartner: S. Schild, S. Biergans

**Comment by SylviaThun** [comment]
GECCO macht keine Vorgaben für Definitionen. Die Angaben sind ggf. in den jeweiligen Studienprotokollen zu finden.
