### ISSUE TITLE
Anamnese Risikofaktoren: Liegen Informationen zur DNR-Anordnung vor?

### ISSUE THREAD

**Issue by sbiergans** [hl7germany/forschungsnetz-covid19#72]
### **Description**

Im Rahmen der Testung des DataDictionary für REDCap durch ein Ärzteteam in Erlangen ist folgende Unklarheit aufgekommen:

- Die Antwortmöglichkeiten „Ja, Wiederbelebung“ und „Nein, keine Wiederbelebung“ sind widersprüchlich. Die Standardfrage klinisch wäre „Ist der Patient DNR?“ – dann wäre die Antwort ja (was dann aber keiner Wiederbelebung entspricht) – oder nein (was dann aber „ja er will wiederbelebt werden“) bedeutet. Deshalb sorgt die derzeitige Auswahl für Verwirrung. Eventuell ist es auch ausreichend in den Antwortmöglichkeiten das Nein durch ein Ja zu ersetzen à Ja, Wiederbelebung/ Ja, keine Wiederbelebung/ Unbekannt

- Anamnese Risikofaktoren: Bei COVID wäre DNI (do not intubate) viel relevanter als DNR (ist im Alltag nicht das gleiche).

### **Contact**

Frage gestellt von: S. Schild
Ansprechpartner: S. Schild, S. Biergans

**Comment by cerbelding** [comment]
**Somehow related to Issues #19 & #40**

**Comment by julsas** [comment]
- Die Frage bezieht sich auf den Inhalt einer DNR-Anordnung. Dort kann angegeben werden, ob der Patient wiederbelebt werden möchte oder nicht.

- DNI (do not intubate) kann im GECCO Plus diskutiert werden, wurde hier nicht gefragt.
