### ISSUE TITLE
Symptome: Fieber

### ISSUE THREAD

**Issue by sbiergans** [hl7germany/forschungsnetz-covid19#73]
### **Description**

Im Rahmen der Testung des DataDictionary für REDCap durch ein Ärzteteam in Erlangen ist folgende Unklarheit aufgekommen:

- Wie ist der Fieber Schweregrad definiert? (Temperatur-Spektren wären hilfreich)

### **Contact**

Frage gestellt von: S. Schild
Ansprechpartner: S. Schild, S. Biergans

**Comment by julsas** [comment]
Angabe von Schweregrad ist optional, kann für Fieber also eggelassen werden.
