### ISSUE TITLE
Medikation: COVID-19-Therapie – Steroide

### ISSUE THREAD

**Issue by sbiergans** [hl7germany/forschungsnetz-covid19#74]
### **Description**

Im Rahmen der Testung des DataDictionary für REDCap durch ein Ärzteteam in Erlangen ist folgende Unklarheit aufgekommen:

- Werden mehrfach abgefragt unter Kortikosteroide und dann noch mal unter Steroide > 0.5 mg/kg und <= 0.5 mg/kg.

### **Contact**

Frage gestellt von: S. Schild
Ansprechpartner: S. Schild, S. Biergans

**Comment by julsas** [comment]
Einmal wird generell gefragt, ob ein Patient Kortikosteroide nimmt. Separat wird nach den zwei konkreten Dosisangaben gefragt.
