### ISSUE TITLE
Medikation: COVID-19-Therapie – Medikamentöse Therapie mit Antikoagulantien

### ISSUE THREAD

**Issue by sbiergans** [hl7germany/forschungsnetz-covid19#75]
### **Description**

Im Rahmen der Testung des DataDictionary für REDCap durch ein Ärzteteam in Erlangen ist folgende Unklarheit aufgekommen:

- Dosis Angabe wäre ggf. interessant.

### **Contact**

Frage gestellt von: S. Schild
Ansprechpartner: S. Schild, S. Biergans

**Comment by julsas** [comment]
Die Dosisangabe ist optional und kann mit FHIR mitgeliefert werden.
