### ISSUE TITLE
Therapie: Bitte dokumentieren Sie die Beatmungstherapie

### ISSUE THREAD

**Issue by sbiergans** [hl7germany/forschungsnetz-covid19#76]
### **Description**

Im Rahmen der Testung des DataDictionary für REDCap durch ein Ärzteteam in Erlangen ist folgende Unklarheit aufgekommen:

- i.d.R. ist die Beatmung erst orotracheal und dann tracheotomiert, wenn der Patient eine Tracheotomie braucht. Wie ist das gemeint in der Auswahl? Wie soll das dokumentiert werden?

### **Contact**

Frage gestellt von: S. Schild
Ansprechpartner: S. Schild, S. Biergans

**Comment by julsas** [comment]
Es sollten Mehrfachangaben möglich sein mit Angabe eines Zeitpunktes/Zeitraumes.
