### ISSUE TITLE
Vitalparameter: Zeitpunkt

### ISSUE THREAD

**Issue by sbiergans** [hl7germany/forschungsnetz-covid19#77]
### **Description**

Im Rahmen der Testung des DataDictionary für REDCap durch ein Ärzteteam in Erlangen ist folgende Unklarheit aufgekommen:

- Es ist essentiell, dass nach einem Zeitpunkt gefragt wird bzw. dieser angegeben werden kann. Beispielsweise die Parameter bei Aufnahme oder der schlechteste Wert insgesamt.

### **further Information**

- geht in die selbe Richtung wie [Issue 54](https://github.com/hl7germany/forschungsnetz-covid19/issues/54)

### **Contact**

Frage gestellt von: S. Schild
Ansprechpartner: S. Schild, S. Biergans

**Comment by SylviaThun** [comment]
Siehe Issue 54
