### ISSUE TITLE
Anamnese: Risikofaktoren

### ISSUE THREAD

**Issue by sbiergans** [hl7germany/forschungsnetz-covid19#78]
### **Description**

Im Rahmen der Testung des DataDictionary für REDCap durch ein Ärzteteam in Erlangen ist folgende Unklarheit aufgekommen:

- OHS (wahrscheinlich obesity hypoventilations syndrom), Schlafapnoe und OSAS (obstr. Schlafapnoesyndrom) sind im Alltag schwer zu unterscheiden, wenn keine schlafmedizinischen Vorbefunde vorliegen. Das sorgt u.U. für Unklarheiten.

- Organtransplantiert: Hinweis, dass i.d.R. Hirnhaut nicht transplantiert wird. (UKER-Arzt); Vermutung, dass bei z.B. Haut, Hornhaut, Gehörknöchelchen, Herzklappen, Blutgefäß, Knochen, Knorpel, Sehne nicht „Ja“ ausgewählt wird, da das im relevanten Sinne keine Organtransplantationen sind. Die für COVID-Verläufe primär interesannte Sache dürfte v.a. die Immunsuppression, also die Einnahme starker Medikamente sein, die die Organtransplantation interessant macht. Dafür fehlt unter Umständen „Knochenmark-Tx“.

### **Contact**

Frage gestellt von: S. Schild
Ansprechpartner: S. Schild, S. Biergans

**Comment by julsas** [comment]
- OHS/OSAS ist durch die SNOMED Codes in der Datensatzbeschreibung definiert.

- Knochenmark-Tx kann für GECCO Plus diskutiert werden.
