### ISSUE TITLE
Falsches Beispiel in PaO2 Observation Resource

### ISSUE THREAD

**Issue by dquell** [hl7germany/forschungsnetz-covid19#83]
Das Beispiel Json für die PaO2 Observation (auf Simplifier), ist identisch zu dem Beispiel in der PaCO2 Observation.
Könnte das auch auf der Simplifier-Seite ausgebessert werden?

PaCO2: https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/PaCO2
PaO2: https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/PaO2

**Comment by julsas** [comment]
Ist geändert. Danke.
