### ISSUE TITLE
mehrere Codes mit gleichem System in FHIR-Ressource

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#85]
**Am Beispiel:** `Cardiovascular Diseases - Zustand nach Revaskularisation`
----

die [in Simplifier hinterlegte Spezifikation des FHIR-Profils](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Disordersofcardiovascularsystem) sieht vor, dass pro Condition nur je 1 Code vom Typ `icd-10-gm`, `sct`, `alpha-id`, `orphanet` eingetragen werden dürfen. (0..1).

Für den Eintrag `Zustand nach Revaskularisation` werden beispielsweise aber die beiden ICD-Codes `Z95.1` und `Z95.5` sowie der SNOMED Code `416940007:363589002=81266008` angegeben. (siehe [Art-Decor](https://art-decor.org/art-decor/decor-datasets--covid19f-?id=2.16.840.1.113883.3.1937.777.53.1.1&effectiveDate=2020-04-08T13%3A04%3A13&conceptId=2.16.840.1.113883.3.1937.777.53.2.1.1120&conceptEffectiveDate=2020-04-08T00%3A00%3A00&language=de-DE) & [Simplifier](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Disordersofcardiovascularsystem))  
Die Validierung der so entstehenden FHIR-Ressource ist jedoch ist daher nicht möglich.

---
**Dieses Problem betrifft die folgenden Profile/Resourcen:**  
- `Cardiovascular Diseases - Zustand nach Revaskularisation` (2x ICD: `Z95.1`& `Z95.5`)
- `Chronische Lebererkankungen - Fettleber` (2x ICD: `K70.0` & `K76.0`)
- `Organtransplantiert - Darm` (2x SNOMED: `181250005` & `181254001`)
- `Krankheitsbegin/Aufnahme - Erkrankungsphase zum Zeitpunkt der Diagnose` (2x SNOMED pro Phase, als `Condition.Stage.Summary`)
- `Symptome - Geruchs- bzw. Geschmacksstörungen`  (2x SNOMED: `36955009` & `44169009`)
- `Komplikationen - Thrombembolische Ereignisse` (2x SNOMED: `439127006` & `414086009`) 
- `Komplikationen - Thrombembolische Ereignisse - Andere` (wie Thromboembolische Ereignisse generell)
und möglicherweise auch noch mehr.

---
Daher sollte von zentraler Stelle festgelegt werden, welche Codierung für diese Antworten einheitlich genutzt wird.

**Comment by cerbelding** [comment]
gilt auch für `Komplikationen.Thrombembolische Ereignisse` & `Komplikationen.Thrombembolische Ereignisse.Andere`

**Comment by julsas** [comment]
- Die beiden ICD Codes `Z95.1` und `Z95.5` drücken unterschiedliche Sachverhalte aus. Wenn man das mit ICD kodieren will, muss man genau wissen, welche Art von Revaskularisation tatsächlich vorliegt. Es ist also nicht so gedacht, dass man beide Codes in eine Ressource schreibt. Wenn beides zutrifft, wie bei `Geruchs- bzw. Geschmacksstörungen`, zwei Instanzen mit jeweils einem Code erzeugen.

- Darm ist ein guter Punkt: `113276009 |Intestinal structure (body structure)|` könnte man hinzufügen im ValueSet.

- Für Thrombembolische Ereignisse könntet ihr `371039008 |Thromboembolic disorder (disorder)|` nutzen.

**Comment by cerbelding** [comment]
Verstehe ich es richtig, dass die Antwortmöglichkeit `Geruchs- bzw. Geschmacksstörungen` also in 2 Antwortmöglichkeiten aufgetrennt werden soll?

**Comment by julsas** [comment]
> Verstehe ich es richtig, dass die Antwortmöglichkeit Geruchs- bzw. Geschmacksstörungen also in 2 Antwortmöglichkeiten aufgetrennt werden soll?

Ich würde das in einem EDC System so lassen und dann zwei Conditions daraus erzeugen.

**Comment by cerbelding** [comment]
Danke!
