### ISSUE TITLE
Codierung für "Andere"

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#86]
Aktuell ist es so, dass die Antwortmöglichkeiten "Andere" in Art-Decor und Simplifier mit einer Reihe von (möglichen) Kodierungen angegeben sind.
Beim Beispiel `Cardiovascular Diseases - Andere` wird die ICD-Range `I00-I99` angegeben.
Die Eintragung von `I00-I99` in die FHIR-Ressource ist jedoch nicht valide, da dieser Eintrag nicht im [ValueSet `CardiovascularDiseasesICD`](https://simplifier.net/forschungsnetzcovid-19/cardiovascular-diseases-icd) vorhanden ist.

Der Validator würde durch den folgenden regulären Ausdruck im ValueSet jeden Code mit `I.` aktzeptieren.  
Soll daher im EDC-System der korrekte ICD-Code abgefragt werden oder soll beispielsweise `I99` (Sonstige und nicht näher bezeichnete Krankheiten des Kreislaufsystems) eingetragen werden?
```json
{
    "system": "http://fhir.de/CodeSystem/dimdi/icd-10-gm",
    "filter":  [
        {
            "property": "concept",
            "op": "regex",
            "value": "^I.*"
        }
    ]
}
```

---
gleiches gilt auch für andere "Andere"

**Comment by cerbelding** [comment]
Alle Codes die laut ValueSet für "Andere" valide sind (z.B. mit `Concept isA XXXXX`) sind zu spezifisch für "Andere"

**Comment by julsas** [comment]
> I00-I99 in die FHIR-Ressource ist jedoch nicht valide
Korrekt, deswegen steht der auch nur zu Anzeigezwecken auf Art-Decor und nicht auf Simplifier.
Der Regex sagt nur, dass alle I-ICD-Codes erlaubt sind. Wenn man "Andere" mit ICD kodieren möchte, muss man sich halt entscheiden.

**Comment by cerbelding** [comment]
Wie @julsas bereits [hier](https://chat.fhir.org/#narrow/stream/179183-german-%28d-a-ch%29/topic/GECCO-Datensatz/near/224034144) erklärt hat, handelt es sich bei dem `concept isA` Filter um den FilterOperator (http://hl7.org/fhir/codesystem-filter-operator.html#filter-operator-is-a),  nicht um das SNOMED-Parent-Concept.
Der vorgeschlagene SNOMED-Code `49601007` erfüllt damit die Anforderungen des ValueSets.

Fazit für uns: 
es werden die beiden Codes `49601007 | Disorder of cardiovascular system (disorder)` und `I51.6 | Herz-Kreislauf-Krankheit, nicht näher bezeichnet` zur Codierung für "Andere" genutzt.

Issue wird daher geschlossen
