### ISSUE TITLE
Ungenutztes Code-Binding für Category-Codes

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#87]
Alle Conditions beinhalten laut FHIR-Profilen in Simplifier ein Code-Binding zwischen dem Eintrag `Condition.Category` und dem [ValueSet `ConditionCategoryCodes`](https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/78838).  
Zusätzlich sind unter `Condition.Category.Coding` die jeweilig passenden Codierungen eingetragen.  

Das Binding ist zwar extensible, triggert bei der Validierung jedoch trotzdem jedes Mal eine Warning:
`WARNING - Keiner der angegebenen Codes ist im Valueset http://hl7.org/fhir/ValueSet/condition-category (http://hl7.org/fhir/ValueSet/condition-category, und ein Code sollte aus diesem Valueset stammen, es sei denn, er enthält keinen geeigneten Code)`

Da das erwähnte ValueSet nur die 2 Einträge `Problem List Item` und `Encounter-Diagnosis` enthält, diese aber an keiner Stelle genutzt werden, könnte dieses Binding doch aufgehoben werden, oder?

**Comment by julsas** [comment]
Stimme dir zu, die Warning jedes Mal ist nervig. Das extensible Binding ist allerdings schon in FHIR Core an der Stelle vorhanden. Extensible kann man dort nicht abschwächen z.B. auf example, um die Warning zu umgehen. Bliebe noch ein ValueSet mit den Diagnosekategorien zu erstellen.

**Comment by cerbelding** [comment]
Dann ignorieren wir das lieber 😆
