### ISSUE TITLE
Falsches Beispiel für Follow-Up Swab Result

### ISSUE THREAD

**Issue by dquell** [hl7germany/forschungsnetz-covid19#89]
Das Beispiel Json für die Follow-Up Swab Result Observation (auf Simplifier), ist das selbe Beispiel wie für SARS-CoV-2-RT-PCR.
Könnte das auch auf der Simplifier-Seite ausgebessert werden?

**Comment by julsas** [comment]
Das ist schon richtig so. Ist auch das selbe Profil. Es wird lediglich nochmal der Labornachweis verlangt.
