### ISSUE TITLE
OrganRecipient: Slice Pattern

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/forschungsnetz-covid19#9]
Aufgrund der Definition des Slicings von Condition.code.coding im [Parent-Profil der MI-I](https://simplifier.net/medizininformatikinitiative-moduldiagnosen/diagnose-duplicate-3) sind die Patterns für System bereits vorgegeben.
Daher ist es redundant, im abgeleiteten Profil, nochmals ein Pattern auf dem Slice zu definieren, das System beinhaltet. Es würde ausreichen, den fixed Value für den Code einzutragen...

**Comment by simoneOnFhir** [comment]
Gerade in Forge kontrolliert, dies scheint bei der Erzeugung des Snapshot zu passieren, dass das Pattern einmal auf code Ebene und dann nochmal in Kombination mit System auf Coding-Ebene erscheint.

...wenn ich schon Probleme mit dem Verständnis habe, wäre es vll. beser mit fixed Values zu arbeiten :D 


Diskussion von für und wieder: https://chat.fhir.org/#narrow/stream/224725-german.2Fcommitters/topic/Pattern.20Slicing

**Comment by patrick-werner** [comment]
Ursache des Problems ist das Parentprofil:
```json
{
                "id":"Condition.code.coding",
                "path":"Condition.code.coding",
                "slicing":{
                    "discriminator": [
                        {
                            "type":"pattern",
                            "path":"system"
                        }
                    ],
                    "rules":"open"
                },
                "min":"1",
                "mustSupport":true
            }
```
Ich würde hier auch mit pattern arbeiten, aber auf Condition.code & discriminator geht auf path: coding.
Dann kann ich immer mit patternCodeableConcept arbeiten und in diesem Pattern meine Anforderungen deklarieren.

**Comment by simoneOnFhir** [comment]
D'accord zu slicing auf pattern/coding.
Ich würde aber im abgeleiteten Profil (sprich: hier) aufgrund der Lesbarkeit neben dem Pattern auch noch mal die fixed values auf Feldebene hinterlegen. Das ist in der Darstellung erheblich deutlicher/verständlicher.
