### ISSUE TITLE
Human immunodeficiency virus infection: ungültige Codierung

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#90]
Das Beispiel zur Implementierung einer[HIV-Infektion aus Simplifier](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Humanimmunodeficiencyvirusinfection-duplicate-2) beinhaltet eine ungültige Codierung:
```json
"code": {
        "coding":  [
            {
                "system": "http://snomed.info/sct",
                "code": "86406008",
                "display": "Human immunodeficiency virus infection"
            }
        ]
    },
``` 
Das [ValueSet `HumanImmunodeficiencyVirusInfections`](https://simplifier.net/forschungsnetzcovid-19/human-immunodeficiency-virus-infections) erlaubt alle Codes mit `Concept isA 86406008` Der hier angegebene Code `86406008` besitzt jedoch `Concept isA 24907000 | Disease caused by Lentivirus (disorder)`.
Der Code `86406008` , welcher in ArtDecor und Simplifier angegeben ist, entspricht damit nicht der Vorgabe! 

Ich bitte darum entweder, (1) eine geeignete Codierung anzugeben oder (2) das ValueSet um den angegebenen Code (`86406008`) zu erweitern.

**Comment by cerbelding** [comment]
gleiches gilt auch für `Malignant neoplastic diseases` mit dem SNOMED-Code `363346000`

**Comment by julsas** [comment]
Ich verstehe die Frage nicht. Wo kommt denn 24907000 | Disease caused by Lentivirus (disorder) her?

**Comment by cerbelding** [comment]
Wie @julsas bereits [hier](https://chat.fhir.org/#narrow/stream/179183-german-%28d-a-ch%29/topic/GECCO-Datensatz/near/224034144) erklärt hat, handelt es sich bei dem `concept isA` Filter um den FilterOperator (http://hl7.org/fhir/codesystem-filter-operator.html#filter-operator-is-a),  nicht um das SNOMED-Parent-Concept.

Issue wird daher geschlossen.

**Comment by cerbelding** [comment]
> 
> 
> Ich verstehe die Frage nicht. Wo kommt denn 24907000 | Disease caused by Lentivirus (disorder) her?

Das ist der Parent des SNOMED-Items. Issue hat sich aber bereits erledigt.
