### ISSUE TITLE
VentilationTypes: alle angegebenen Codierungen ungültig

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#91]
Die für `VentilationTypes` angegebenen SNOMED Codes sind nicht im [ValueSet `RespiratoryTherapies`](https://www.netzwerk-universitaetsmedizin.de/fhir/ValueSet/respiratory-therapies) enthalten und werden durch den Validator daher abgelehnt!  

**durch das ValueSet akzeptiert:** `Include codes from SNOMED_CT where concept IsA 53950000`  

**In Simplifier & ArtDecor angegeben:**

| answer | [Simplifier](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Ventilationtype) | [ArtDecor](https://art-decor.org/art-decor/decor-datasets--covid19f-?id=2.16.840.1.113883.3.1937.777.53.1.1&effectiveDate=2020-04-08T13%3A04%3A13&conceptId=2.16.840.1.113883.3.1937.777.53.2.1.1810&conceptEffectiveDate=2020-04-08T00%3A00%3A00&language=de-DE) | Problem |
| --- | --- | --- | --- |
| Nasal High-Flow-Sauerstoff-Therapie | 371907003 (aus Beispiel) |  371907003:425391005=426854004 | für `371907003` gilt `Concept isA 57485005 Oxygen therapy` &rarr; erfüllt ValueSet-Kriterien nicht |  
| Nicht-invasive Beatmung |  | 428311008 | für `428311008 ` gilt `Concept isA 40617009 Artificial respiration` &rarr; erfüllt ValueSet-Kriterien nicht |
| invasive Beatmung (orotracheal) |  | 40617009:425391005=26412008 | für `40617009` gilt `Concept isA 266700009 Assisted breathing` &rarr; erfüllt ValueSet-Kriterien nicht. |
| invasive Beatmung (tracheotomie) |  | 40617009:425391005=129121000 | für `40617009` gilt `Concept isA 266700009 Assisted breathing` &rarr; erfüllt ValueSet-Kriterien nicht. |

Für die letzten beiden (inv. Beatmung) existieren auch diese 3 Zusatz-Codes: 
- `425391005 | Using access device (attribute)`
- `26412008 | Endotracheal tube, device (physical object)`
- `129121000 | Tracheostomy tube, device (physical object)`

Alle angegebenen Codierungen sind damit ungültig, wenn gegen die festgelegten Profile validiert!  
Die Procedure-Codes befinden sich allesamt mindestens 1 Hierarchieebene tiefer als die, das ValueSet erfüllenden Codes.

Welche Codierung soll also verwendet werden?

**Comment by cerbelding** [comment]
ähnliches Problem bei "Anamnesis - RespiratoryTherapies" wo der im Beispiel angegebene Code `53950000` nicht dem ValueSet (alle Codes mit `Concept isA 53950000`) entspricht

**Comment by julsas** [comment]
> für 428311008 gilt Concept isA 40617009 Artificial respiration → erfüllt ValueSet-Kriterien nicht
Die Kriterien sind erfüllt, weil 428311008 |Noninvasive ventilation (procedure)| unter 40617009 |Artificial respiration (procedure)|.
Nochmal: is-a operator in dem ValueSet != SNOMED is-a in der Hierachie nach oben. http://hl7.org/fhir/codesystem-filter-operator.html#filter-operator-is-a
Und die postkoordinierten Codes kann man nicht validieren.

**Comment by cerbelding** [comment]
Wie @julsas bereits [hier](https://chat.fhir.org/#narrow/stream/179183-german-%28d-a-ch%29/topic/GECCO-Datensatz/near/224034144) erklärt hat, handelt es sich bei dem `concept isA` Filter um den FilterOperator (http://hl7.org/fhir/codesystem-filter-operator.html#filter-operator-is-a),  nicht um das SNOMED-Parent-Concept.

Issue wird daher geschlossen
