### ISSUE TITLE
Malignant neoplastic diseases: ungültige Codierung

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#92]
Das Beispiel zur Implementierung einer [MND-Condition aus Simplifier](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Malignantneoplasticdiseases) beinhaltet 2 gemäß ValueSet ungültige Codierung:
```json
"code": {
        "coding":  [
            {
                "system": "http://snomed.info/sct",
                "code": "86406008",
                "display": "Human immunodeficiency virus infection"
            }
        ]
    },
``` 
Das [ValueSet `MalignantNeoplasticDiseases`](https://simplifier.net/forschungsnetzcovid-19/malignant-neoplastic-diseases/) erlaubt alle Codes mit `Concept isA 363346000` Der hier angegebene Code `363346000` besitzt jedoch `Concept isA 55342001 | Neoplastic disease (disorder)`.
Der Code `363346000` , welcher in ArtDecor und Simplifier angegeben ist, entspricht damit nicht der Vorgabe! 

Das [ValueSet `MalignantNeoplasticDiseasesIcd`](https://simplifier.net/ForschungsnetzCovid-19/malignant-neoplastic-diseases-icd/) erlaubt alle Codes mit `concept Regex ^C.*` Der hier angegebene Code `C80.9` entspricht jedoch, wie alle ICD-Codes, diesem Regulären Ausdruck nicht.

Ich bitte darum entweder, (1) eine geeignete Codierung anzugeben oder (2) das SNOMED-ValueSet um den angegebenen Code (`86406008`) zu erweitern bzw. den regulären Ausdruck im ICD-ValueSet anzupassen.

**Comment by cerbelding** [comment]
corellated to Issue #90

**Comment by julsas** [comment]
Du wirfst hier HIV mit Onkologie durcheinander. 86406008 |Human immunodeficiency virus infection (disorder)| steht in SNOMED natürlich nicht unter 363346000 |Malignant neoplastic disease (disorder)|. Deswegen verstehe ich die Frage nicht. Und der Regex ^C.* matcht alle ICD-Codes beginnend mit C.

**Comment by cerbelding** [comment]
Beim HIV-Profil besteht nur das identische Problem. Zusammenhängend sind sie damit nicht.

Beim ICD-Code habe ich den RegEx falsch gelesen. Ich ging von `^C\.*` aus.

**Comment by cerbelding** [comment]
Wie @julsas bereits [hier](https://chat.fhir.org/#narrow/stream/179183-german-%28d-a-ch%29/topic/GECCO-Datensatz/near/224034144) erklärt hat, handelt es sich bei dem `concept isA` Filter um den FilterOperator (http://hl7.org/fhir/codesystem-filter-operator.html#filter-operator-is-a),  nicht um das SNOMED-Parent-Concept.

Issue wird daher geschlossen
