### ISSUE TITLE
StageAtDiagnosis: falsches/ungültiges Code-Binding

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#93]
Die Ressource [`OnsetOfIllness - StageAtDiagnosis`](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Stageatdiagnosis) beinhaltet ein falsches/ungültiges Code-Binding.  
Laut Simplifier MUSS der SNOMED-Code aus dem [ValueSet `diagnosis-codes` (https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/ValueSet/diagnoses-sct)](https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.diagnose/1.0.1/files/294195) stammen.  

Dieses ValueSet gibt als Filter die Optionen `concept isA 404684003`, `concept isA 272379006` und `concept isA 243796009` vor.  
Der im Beispiel genutzte Code `840539006` für COVID-19 erfüllt diese Vorraussetzungen nicht.
Weder der HAPI-Validator, noch der von @julsas genannte HL7 FHIR-Validator (in Verbindung mit dem [GECCO IG-Package](https://simplifier.net/packages/de.gecco/1.0.2/)) können die Beispielressource oder daran angelehnte Ressourcen validieren.

**Die Fehlermeldung lautet:**
`The code provided (http://snomed.info/sct#840539006) is not in the value set https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/ValueSet/diagnoses-sct, and a code from this value set is required: The code provided (http://snomed.info/sct#840539006) is not valid in the value set &#39;diagnoses-codes&#39; (from http://tx.fhir.org/r4)`

**Comment by julsas** [comment]
840539006 is-a disorder is-a clinical finding. So wie es in dem MII ValueSet steht. Die Definition stimmt schon so. Ich schätze weil der Covid-19 Code relativ neu ist, kennt der Validator den noch nicht. Den Fehler wirst du bei allen SNOMED Terms bekommen, die erst in dem Pre-Release waren.

**Comment by cerbelding** [comment]
Danke für die Info!
