### ISSUE TITLE
VitalSigns: falsche Kardinalität für Category-Coding

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#94]
Der Implementation-Guide für verschiedene `VitalSigns` (u.a. PaCO2, PaO2, FiO2, pH) gibt die Kardinalität von `Category.Coding` mit 2..* an.

Nach meiner Einschätzung sollte das 1..* sein, da das jeweilige Coding ja mehrfache Codes (in diesem Fall LOINC-Codes) enthalten kann, und dazu nicht mehrere Codings existieren müssen.

Hier muss das Profil ggf. angepasst werden.

**Comment by julsas** [comment]
Die Kardinalität 2..* kommt schon aus dem MII Modul Labor und lässt sich nicht auf 1..* ändern. https://simplifier.net/medizininformatikinitiative-modullabor/observationlab 
Damit wird sichergestellt, dass einmal das HL7 ValuSet und LOINC für die Kategorie genutzt wird. Da die beiden Slices 1.. Kardinalität haben, muss Coding minimum 2.. sein.

**Comment by cerbelding** [comment]
Verstehe, danke für die Erklärung.
