### ISSUE TITLE
Symptome deutsche designations

### ISSUE THREAD

**Issue by julsas** [hl7germany/forschungsnetz-covid19#95]
beim Zusammenstellen lokaler Daten sind ein paar Unstimmigkeiten im ValueSet 'SARSCoV2Symptoms' aufgefallen:
•	Übersetzung 38880002  Rigor (finding) ->  Fieber
•	Übersetzung 91175000  Seizure (finding) -> Starre
•	Tippfehler Überlkeit
•	Außerdem halten wir das Einbeziehen von "84387000 Asymptomatic (finding)" in dieses ValueSet für fragwürdig. Alle anderen Einträge sind Symptome, die mithilfe eines Fragebogens erhoben werden können. Auch eine Angabe u.a. der "Severity" ist für "asymptomatisch" problematisch.

**Comment by JohannesOehm** [comment]
Zu dem Punkt aymptomatic: Das ist mir auch gerade nicht so ganz klar. Unser Formular hat derzeit folgende Logik:

Liegen Symptome vor? Ja /Nein /Unbekannt
Wenn ja, blende Liste ein mit Symptomen und Ja/Nein/Unbekannnt, 
Wenn Symptom Ja, blende für Symptom Dropdown "Schweregrad" ein.


Soll dann nur das Symptom "asymptomatisch" übermittelt werden, wenn keine Symptome vorliegen, 
oder sollen wir dann auch für alle Symptome Ressourcen mit Nein oder Unbekannt erzeugen?

Und wenn Symptome vorliegen, soll dann asymptomatic = refuted übermittelt werden?

Viele Grüße
Johannes

**Comment by julsas** [comment]
Hallo @JohannesOehm,
wenn keine Symptome vorliegen, übermittelt asymptomatisch und die anderen Symptome mit Nein oder Unbekannt, wenn ihr das so ausführlich erfasst. Bei Vorliegen von Symptomen, dann entsprechend asymptomatisch verneinen. Dann habt ihr die Angaben komplett.

**Comment by JohannesOehm** [comment]
Alles klar, werden wir so machen. Danke für die Auskunft!
