### ISSUE TITLE
analyseBefundCode: unklare Code-Nutzung

### ISSUE THREAD

**Issue by cerbelding** [hl7germany/forschungsnetz-covid19#96]
Einige FHIR-Ressourcen, welche Laboruntersuchungen beschreiben (Laborwerte, VitalSigns, Outcome.FollowUpSwabResult) erfordern die verpflichtende Angabe eines `analyseBefundCode`s.  

Auf den ersten Blick enthält dieser Code im [Beispiel für `FollowUpSwabResult`](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Follow-upswabresult) den entsprechenden LOINC Code inklusive Display (`94500-6_SARS-CoV-2-RNA-Presence-in-Respiratory-specimen`), sowie ein lokales CodeSystem (`https://www.charite.de/fhir/CodeSystem/lab-identifiers`).  

Ist hier ein CodeBinding auf ein vorgegebenes ValueSet (beispielsweise [`LaboratoryTestsGECCO`](https://www.netzwerk-universitaetsmedizin.de/fhir/ValueSet/lab-tests-gecco) / [hier im GitHub](https://github.com/hl7germany/forschungsnetz-covid19/blob/master/terminologie/valuesets/ValueSet-lab-tests-gecco.xml)) mit LOINC-Codes geplant oder könnte der Code hier genau so gut `12345` lauten?
Soll das CodeSystem standortspezifisch unterschiedlich sein?

**P.S.:** 
Da [`FollowUpSwabResult`](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Follow-upswabresult) und [`SARS-CoV-2-RT-PCR`](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/SARS-CoV-2-RT-PCR) beide das gleiche FHIR-Profil (https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-rt-pcr) nutzen, ist in den Beispielen der `Identifier`-Abschnitt identisch und damit nicht unique.

**Comment by cerbelding** [comment]
CodeBinding ist aufgrund der uniqueness eines Identifiers wohl ausgeschlossen.

**Comment by julsas** [comment]
Identifier ist der lokale Business-Identifer und kann standortspezifisch selbst vergeben werden. Die Beispiele orientieren sich am Labor-IG der MII. Dort heißt es: `Observation muss eindeutig identifizierbar sein, keine Vorgaben zur Kodierung, Präferenz: 'LOINC CODE_Befundnummer'`
Ihr könnt da aber auch was anderes, wie `12345` nutzen.

**Comment by cerbelding** [comment]
Ok. Danke!
