### ISSUE TITLE
"Other" Option bei Chronischen Lebererkrankungen

### ISSUE THREAD

**Issue by dquell** [hl7germany/forschungsnetz-covid19#97]
Bei der Implementation der ChronicLiverDiseases Resource ist uns die Option "Other" aufgefallen.
Wenn bekannt ist das der Patient eine chronische Lebererkrankung hat, diese aber nicht unter die 4 angegebenen Krankheiten + Snomed Codes fällt würden wir diese unter "Other" einsortieren.
Dafür gibt es aber leider kein Beispiel auf der Simplifier Seite.
Wie soll dieses Other implementiert werden, bzw. welcher Snomed Code sollte dafür verwendet werden?

**Comment by cerbelding** [comment]
Für den `ODM2FHIR` Mapper, welcher aus den CDISC-ODM Exporten aus REDCap & DIS valide FHIR-Ressourcen erstellt, haben wir es folgendermaßen gemacht:

**`Condition.code.coding[x]`:** 
* SNOMED-Code `328383001 | Chronic liver disease (disorder)`
* ICD-Code `K76.9 | Leberkrankheit, nicht näher bezeichnet`

die eigentliche Antwort dann gemäß Beispiel mittels `clinicalStatus` & `verificationStatus` bzw. `UncertaintyOfPresence`-Extension

Das Freitextfeld zur Beschreibung der Option "Andere" wird dann als `Condition.code.text` hinterlegt.
