### ISSUE TITLE
StageAtDiagnosis

### ISSUE THREAD

**Issue by JohannesOehm** [hl7germany/forschungsnetz-covid19#98]
Hallo, 
Bei dem Profil https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/diagnosis-covid-19 wird für `Condition.stage.summary.coding` via Slicing maximal ein SNOMED-Code erlaubt. Gleichzeitig sollen aber laut Implementation Guide die Uncomplicated, Complicated und Critical Phase mit zwei SNOMED-Codes spezifiziert werden (https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Stageatdiagnosis). Oder verstehe ich da etwas falsch?

**Comment by cerbelding** [comment]
Hallo @JohannesOehm,
ein ähnliches Problem habe ich auch in Issue #85 angesprochen.
Es ist offenbar nicht vorgesehen, mehrere Codes des gleichen Systems zu verwenden. 

Wir haben es für den [`ODM2FHIR`-Mapper](https://github.com/num-codex/odm2fhir), welcher aus den CDISC-ODM Exporten aus REDCap & DIS valide FHIR-Ressourcen erstellt, folgendermaßen gemacht:
- uncomplicated phase --> 255604002 | Mild (qualifier value)
- complicated phase --> 6736007 | Moderate (severity modifier) (qualifier value)
- critical phase --> 24484000 | Severe (severity modifier) (qualifier value)
- recovery phase -> 277022003 | Remission phase (qualifier value)
- dead --> 399166001 | Fatal (qualifier value)
- unknown --> 261665006 | Unknown (qualifier value)

**Comment by JohannesOehm** [comment]
Alles klar, dann werde ich auch dieses Mapping bei uns verwenden. Vielen Dank für die schnelle Antwort!
